### ISSUE TITLE
Workloads API support (DaemonSet, Deployment and StatefulSet)

### ISSUE THREAD

**Issue by cemo** [terraform-providers/terraform-provider-kubernetes#100]
Since Kubernetes 1.9 Workloads API is GA. Supporting them would be unbelievable. 

> Workloads API GA
> We’re excited to announce General Availability (GA) of the apps/v1 Workloads API, which is now 
> enabled by default. The Apps Workloads API groups the DaemonSet, Deployment, ReplicaSet, and > StatefulSet APIs together to form the foundation for long-running stateless and stateful workloads > in Kubernetes. Note that the Batch Workloads API (Job and CronJob) is not part of this effort and > will have a separate path to GA stability.

PS: 

I am not sure why kubernetes provider in the first place has been developed but now I think that it is best and clearest way to configure Kubernetes resources.  Configuring and maintaining Helm is tedious and error prone. People are looking for [alternative] ways and I think that Terraform is the best option right now.

[alternative]: https://dzone.com/articles/terraform-vs-helm-for-kubernetes

**Comment by nickschuch** [comment]
Started working on a PR here https://github.com/terraform-providers/terraform-provider-kubernetes/pull/101

**Comment by MarcusNoble** [comment]
Now that Deployments is merged in is there anyone working on the other resources?

We're currently in need of DaemonSets in order to configure a new AWS based kubernetes cluster with Kube2IAM setup.

**Comment by bennettellis** [comment]
See this fork: https://github.com/sl1pm4t/terraform-provider-kubernetes if you need other configurations sooner rather than later. It works well, and is very, very easy to build with docker approach.

**Comment by mafrosis** [comment]
@sl1pm4t Do you have plans to package up the work in your fork as P/Rs on this repo? As mentioned [here](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/101#issuecomment-352279208).

**Comment by aldoborrero** [comment]
I've using @sl1pm4t repository and I have to say that works quite well, so definitely I propose to use his work to be proposed as a PR for the official provider (otherwise this one is half baked).

**Comment by cemo** [comment]
This seems to be closed since all resources are implemented.
