### ISSUE TITLE
Feature request: add kubernetes_network_policy resource

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-kubernetes#110]
Please add support for Kubernetes NetworkPolicy resource.

### Affected Resource

- kubernetes_network_policy

### Terraform Configuration Files

```hcl
resource "kubernetes_namespace" "example" {
  metadata {
    name = "terraform-example-namespace"
  }
}

# NOT IMPLEMENTED YET
resource "kubernetes_network_policy" "allow_all" {
  metadata {
    name = "allow-all"
    namespace = "${kubernetes_namespace.example.metadata.0.name}"
  }

  spec {
    pod_selector = {}
    ingress = [{}]
    egress = [{}]
  }
}

```

### References

- API reference: https://kubernetes.io/docs/api-reference/v1.9/#networkpolicy-v1-networking

**Comment by pdecat** [comment]
Started work on this.

Note: supporting egress and policyTypes would require updating kubernetes/client-go and kubernetes/api dependencies to 1.8+ compatible versions.

**Comment by GuiSim** [comment]
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/118

Looks like this introduces the new network policy resources and was merged today.

**Comment by pdecat** [comment]
Indeed!
