### ISSUE TITLE
Feature Request: Kubernetes Service data source

### ISSUE THREAD

**Issue by elblivion** [terraform-providers/terraform-provider-kubernetes#13]
Hi,

We are using Kubernetes itself to create the LoadBalancer type Services as AWS ELBs. It would be great to be able to extract the corresponding ELB dns name (`status.loadbalancer.ingress.hostname`) from a data source in Terraform so we can e.g. create a Route 53 CNAME or ALIAS A RR pointing to it.

Thanks,
Anthony

**Comment by radeksimko** [comment]
Thanks for submitting this issue.

I think there are a few caveats as service doesn't have to be always `Type=LoadBalancer` and the LB might not expose a hostname, so you'll only get an IP, but otherwise this sounds like a good idea.
