### ISSUE TITLE
Feature Request: add reclaimPolicy to kubernetes_storage_class resource

### ISSUE THREAD

**Issue by nocon** [terraform-providers/terraform-provider-kubernetes#131]
Please add reclaimPolicy field to the storage class resource. Documented [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#storageclass-v1-storage).

**Comment by costimuraru** [comment]
👍

**Comment by sebastianvoss** [comment]
[Mount options](https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options) would be also helpful.

**Comment by BusraKoken** [comment]
I see that the implementation is already in the master(https://github.com/terraform-providers/terraform-provider-kubernetes/commit/eed77a7cb8cb5240d2bfaf198500790cce23a1df). Thanks for that! :) 

I was wondering when is the new release of this provider so that we can start using this feature?

**Comment by arbourd** [comment]
I believe this was released `1.4.0` and can be closed?
