### ISSUE TITLE
FR: Support mount_options for PersistentVolumes

### ISSUE THREAD

**Issue by dploeger** [terraform-providers/terraform-provider-kubernetes#146]
### Terraform Version
v0.11.4

### Affected Resource(s)
- kubernetes_persistent_volume

### Expected Behavior
Kubernetes 1.9 supports the option mount_options in their [PersistentVolumeSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#persistentvolumespec-v1-core), where the operator can add specific options, that should be used when mounting the volume. This option is currently missing from the terraform kubernetes provider.

### References

- [kubernetes-168](https://github.com/kubernetes/features/issues/168)

**Comment by jeff1985** [comment]
This is currently a big blocker for me to use persistent volumes. At the moment I'm using a workaround and deploy persistent volume via yaml files directly to the cluster. Are there any plans to implement this functionality?

**Comment by mjeco** [comment]
+1 for this feature. Currently, I use a local-exec provisioner to add the mount options to the volume created by terraform. It would be really useful to specify the mont options directly.

**Comment by atb00ker** [comment]
If someone has a trick for using `nfsvers==4.1`, I'd love to see it! :smile:

**Comment by dploeger** [comment]
@jrhouston  Why was this closed? Was it implemented somewhere?
