### ISSUE TITLE
kubernetes_replication_controller update does not affect  running pods

### ISSUE THREAD

**Issue by pat-nomalab** [terraform-providers/terraform-provider-kubernetes#158]
Hello,
I'm trying to update container image of running pods in a replication controller, I've  managed to update the replication controller definition but the pods are not updating.

### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.10.0
+ provider.kubernetes v1.1.0
```
### Affected Resource(s)
```
- kubernetes_replication_controller
```
### Terraform Configuration Files
```javascript
resource "kubernetes_replication_controller" "default" {
  "metadata" {
    name = "default"
    labels {
      app = "myapp"
    }
  }

  "spec" {
    replicas = 3

    "selector" {
      app = "myapp"
    }

    template {
      container {
        name = "myapp"
        image = "nginxdemos/hello"
        #image = "nginxdemos/hello:plain-text"

        port {
          container_port = 80
        }
      }
    }
  }
}
```

### Expected Behavior
Replication controller is updated
Pods are updated with new image

### Actual Behavior
Replication controller is updated
Pods are not update, you need to scale down and scale up to apply changes

### Steps to Reproduce
1. changes container image
2. `terraform apply`

### Important Factoids
Running in google cloud

**Comment by auberryberry** [comment]
+1 seeing the same behaviour on AKS

**Comment by pdecat** [comment]
If the replication controller is properly updated, I guess it is not an issue with `terraform-provider-kubernetes` but rather the normal kubernetes behavior.

Or do you expect the terraform provider to also trigger a rolling update?

https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/

**Comment by paultyng** [comment]
Unfortunately, as the docs say, this is what the deployment in Kubernetes is meant for, not something that we would handle in the provider.

> Note: The preferred way to create a replicated application is to use a [Deployment](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#deployment-v1-apps), which in turn uses a [ReplicaSet](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#replicaset-v1-apps). For more information, see [Running a Stateless Application Using a Deployment](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/).
