### ISSUE TITLE
Kubernetes endpoints resource is not implemented

### ISSUE THREAD

**Issue by plispe** [terraform-providers/terraform-provider-kubernetes#167]
Is there is any reason why Kubernetes endpoints resource is not supported by the Terraform kubernetes provider? I know, that endpoints are in most cases handled not directly but through Kubernetes service. But I have a use case with [glusterfs](https://docs.openshift.org/latest/install_config/storage_examples/gluster_example.html) persistent volumes where I need to define endpoints manualy. This is currenty not possible with Kubernetes provider, despite the fact that endpoints is stable api v1 resource.

**Comment by mwpaa** [comment]
I've hit this same roadblock now, not wanting to use a forked repo though. Might just have to implement a PR myself.

**Comment by orkenstein** [comment]
That would be sweet to get this in new version ASAP

**Comment by alexsomesan** [comment]
Support for endpoints will be released in 1.6.0

**Comment by BouchaaraAdil** [comment]
@alexsomesan please update docs here https://github.com/terraform-providers/terraform-provider-kubernetes/issues/167 to  include it, i see that the resource is already released on `1.6.0`

**Comment by BouchaaraAdil** [comment]
@alexsomesan please update docs here https://www.terraform.io/docs/providers/kubernetes/index.html to  include it, i see that the resource is already released on `1.6.0`
