### ISSUE TITLE
Suggesting to add kubernetes deployment resource

### ISSUE THREAD

**Issue by SecurityNeo** [terraform-providers/terraform-provider-kubernetes#172]
Hi team,

Currently，terraform kubernetes provider don't support kubernetes_deployment resource,only surpport kubernetes_rc,we need a better upgrating plan for our application what kubernetes_rc don't give us,so  it would be nice to have kubernetes_deployment as well.

thanks.

**Comment by lfshr** [comment]
Dupe of #3

**Comment by bflad** [comment]
Thanks @lfshr, that appears to be the case. Closing this issue in preference of the earlier #3 to consolidate discussion and efforts.
