### ISSUE TITLE
Interested in helping HashiCorp maintain this provider full time?

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-kubernetes#178]
I manage the team at HashiCorp that works on providers internally. 

I am looking for someone to help us improve our Kubernetes provider support and implement some of the roadmap we have planned for it, if you are interested, [please apply](https://grnh.se/bb467cff1).

This job is a full time maintainer for the Kubernetes provider.

**Comment by jhelblinghh** [comment]
@paultyng FYI
The page you are looking for was moved, removed, renamed, or may never have existed.

**Comment by paultyng** [comment]
@jhelbling sorry about that, issue in Greenhouse, its back up now.

**Comment by OGProgrammer** [comment]
If I knew more GO I'd be all over this.

**Comment by sarneaud** [comment]
Heads up: the link seems to be broken again.

**Comment by lainra** [comment]
The related position is: https://www.hashicorp.com/jobs/1288355
(I'm not affiliated with Hashicorp, just hoping like everyone that they find a full-time maintainer for this plugin :) )

**Comment by paultyng** [comment]
This position is filled!

**Comment by alexsomesan** [comment]
@jon-butterworth Support for deployments was released a few weeks ago. It's already available.

https://www.terraform.io/docs/providers/kubernetes/r/deployment.html

There is a small issue with waiting for deployments to finish for which we merged a fix that will go into the upcoming release. If you don't depend on that waiting feature, you can already use deployments.

**Comment by jon-butterworth** [comment]
@alexsomesan Great, thanks. Apologies, I must have missed that. I'll check it out now.

**Comment by alexsomesan** [comment]
No worries. Let me know how they work for you and if you run into any issues (other than the one I mentioned).

**Comment by jon-butterworth** [comment]
@alexsomesan Are there any full and in depth examples to help with syntax and formatting? The documentation is a touch thin. I'm transposing from a yaml deployment to hcl for TF. I'm mustering my way through at the moment, but I can't help but think I'm formatting a bunch of stuff wrong :)

**Comment by alexsomesan** [comment]
@jon-butterworth May I suggest you have a look at the acceptance tests for the deployment resource:

**Comment by alexsomesan** [comment]
https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_deployment_test.go

In the second half of the file you get a few HCL block that are the deployment configurations we use to test the resource.

**Comment by jon-butterworth** [comment]
Great, thanks. This looks just like what I need. I'll go through this.

**Comment by jon-butterworth** [comment]
@alexsomesan I'm seeing `liveness_probe` in the tests, but not `readiness_probe`. Is `readinessProbe` not a feature in this resource?

**Comment by jon-butterworth** [comment]
Is that what you're referring to here: 

> There is a small issue with waiting for deployments to finish for which we merged a fix that will go into the upcoming release. If you don't depend on that waiting feature, you can already use deployments.

**Comment by jon-butterworth** [comment]
Another thing if I may @alexsomesan (also let me know if this is not the best forum for these type questions.) - Happy to direct them somewhere more suitable.

I am trying to transpose the following from my yaml file to the deployment resource:
```
      volumes:
      - name: artifactory-pro-volume
        persistentVolumeClaim:
          claimName: artifactory-claim
      imagePullSecrets:
      - name: docker-reg-secret
```
Is this handled inside `volume` or `persistent_volume_claim` from within metadata, or by the `kuberneted_pod` resource?

The test is great for most of what I'm transposing, however I'm struggling to see some of the key/values I need to set.

I'll upload my files when working, to alleviate future questions like this.

**Comment by paultyng** [comment]
@jon-butterworth it should support both `liveness_probe` and `readiness_probe`, it has all the same attributes as containers/pods do in the deployments pod template (they share the same provider code that lists the configuration options) so you can also look at the pod reference for some of the details: https://www.terraform.io/docs/providers/kubernetes/r/pod.html#readiness_probe

If you are seeing additional issues, please open a new issue for them, your comments may get lost in here. If you have questions about usage you can also find some help in some of the community slack rooms (HangOps, Kubernetes, etc.).
