### ISSUE TITLE
Feature Request:  Support for Kubernetes Endpoints for Headless Services

### ISSUE THREAD

**Issue by marty2bell** [terraform-providers/terraform-provider-kubernetes#184]
### Terraform Version

Terraform v0.11.7
+ provider.kubernetes v1.2.0

### Expected Behavior

For headless services, there needs to be a kubernetes endpoint defined with the same name as the service when we don't need any load balancing etc....

To support this in terraform, we need be be able to create Endpoint resources via the kubernetes provider and ensure the service resource allows for non clustered service types, type defaults to ClusterIP, but cluster_ip can be set to None.

**Comment by alexsomesan** [comment]
Endpoints were introduced by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/350 and released in v1.6.1
