### ISSUE TITLE
Kubernets Replication Controller image update 

### ISSUE THREAD

**Issue by ictcontact** [terraform-providers/terraform-provider-kubernetes#186]
Hello,
I'm trying to update container image of running pods in a replication controller, I've managed to update the replication controller definition but the pods are not updating.

Terraform Version
Terraform v0.11.7
+ provider.aws
+ provider.kubernetes ~> v1.1

Affected Resource(s)
- kubernetes_replication_controller
Terraform Configuration Files

resource "kubernetes_replication_controller" "main" {
  metadata {
    name = "${local.service_full_name}"

    labels {
      App = "${local.service_full_name}"
    }
  }

  spec {
    replicas = "${var.cluster_environment == "prod" ? "${var.service_replicas}" : 1}"

    selector {
      App = "${local.service_full_name}"
    }

    template {
      image_pull_secrets = {
        name = "dockerhub"
      }

      container {
        image             = "${var.service_image}"
        image_pull_policy = "Always"
        name              = "${local.service_full_name}"
 port {
          container_port = 80
        }
      }
    }
  }
}

Expected Behavior
Replication controller is updated
Pods are updated with new image

Actual Behavior
Replication controller is updated
Pods are not update, you need to delete pod to apply changes

Steps to Reproduce
changes container image
terraform apply

Important Factoids
Running in aws eks

**Comment by pdecat** [comment]
Hi, this is the expected behavior for replication controllers, as the terraform provider does not perform rolling updates: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/158#issuecomment-391713713

**Comment by pdecat** [comment]
That's it.

**Comment by ictcontact** [comment]
@pdecat Thanks!

**Comment by Madhav1217** [comment]
Hi Friends 
i worked on kubernetes update container using makefile  i confused that file can you help me
