### ISSUE TITLE
kubernetes_replication_controller doesn't restart correctly 

### ISSUE THREAD

**Issue by mkyc** [terraform-providers/terraform-provider-kubernetes#190]
### Terraform Version
✗ terraform -v
Terraform v0.11.8
+ provider.azurerm v1.17.0
+ provider.kubernetes v1.2.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
- kubernetes_replication_controller

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "kubernetes_replication_controller" "test" {
  metadata {
    name      = "${var.env["short"]}-${var.test["app_name"]}"
    namespace = "${kubernetes_namespace.main.metadata.0.name}"
  }

  spec {
    replicas = "${var.test["replicas"]}"

    selector {
      app = "${var.env["short"]}-${var.test["app_name"]}"
    }

    template {
      container {
        image             = "${var.test["docker_registry_url"]}/${var.test["docker_container_name"]}:${var.deployment_image_tag}"
        name              = "${var.env["short"]}-${var.test["app_name"]}"

        port {
          container_port = "${var.test["container_port"]}"
        }
      }
    }
  }
}
```

### Expected Behavior
recreate kubernetes_replication_controller.test correctly

### Actual Behavior
replication controller is correctly removed but (I think) destruction is asynchronous and creation fails. 

```bash
kubernetes_replication_controller.test: Destroying... (ID: test/ab-test)
kubernetes_replication_controller.test: Destruction complete after 1s
kubernetes_replication_controller.test: Creating...
  metadata.#:                                                  "" => "1"
  [...]

Error: Error applying plan:

1 error(s) occurred:

* kubernetes_replication_controller.test: 1 error(s) occurred:

* kubernetes_replication_controller.test: Failed to create replication controller: object is being deleted: replicationcontrollers "ab-test" already exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

### Steps to Reproduce

1. change some value in rc. 
1. `terraform apply`

### Important Factoids
Running cluster on AKS.

**Comment by aeneasr** [comment]
I am experiencing a similar issue, with either `already exists` or `not found` as an error message. Any way to fix this?

**Comment by mkyc** [comment]
I'm not sure if it shouldn't be closed. Now it's possible to migrate to deployments and provider version in this ticket is bit old. Generally do `terraform init -upgrade` sometimes ;)
