### ISSUE TITLE
Feature Request: kubernetes_replication_controller should support pod metadata

### ISSUE THREAD

**Issue by npbool** [terraform-providers/terraform-provider-kubernetes#192]
I need to add annotations to Pods inside a ReplicationController. According to kubernetes doc for ReplicationController,

> The .spec.template is a pod template. It has exactly the same schema as a pod, except it is nested and does not have an apiVersion or kind.

But kubernetes_replication_controller.spec.template doesn't have a metadata argument.

Terraform version:
Terraform v0.11.9

**Comment by pdecat** [comment]
I believe it is the same as #106

**Comment by pdecat** [comment]
Hi @alexsomesan, I believe this one can be closed as it was resolved by #193.

**Comment by alexsomesan** [comment]
True! Thanks for pointing it out.
Warping this one up.
