### ISSUE TITLE
Feature Request: Service data source

### ISSUE THREAD

**Issue by mbarrien** [terraform-providers/terraform-provider-kubernetes#207]
I have a Kubernetes service being deployed outside of this provider (specifically, the Kubernetes Helm provider). It  is a NodePort service, for which Kubernetes assigns a random port. I would like to be able to feed this port into an aws_security_group_rule to be able to open up that port to an ALB load balancer's security group. However, I have no way using this provder to query the Service to get the assigned NodePort so that I can restrict that rule very specifically to that port rather than all ports in the --service-node-port-range.

The Kubernetes provider should provide a data source for Service that can return the spec of an existing Service, including the ports in the spec. Ideally, it would be able to return any data provided by Kubernetes in a way that can be fed to other resources.

(The provider ideally should provide data sources for each of the existing resources that do not attempt to create the resource, in case it is externally managed, but I'll leave this issue focused on the Service data source).

**Comment by florianrusch** [comment]
I think this issue can be closed. Feature is already implemented: https://www.terraform.io/docs/providers/kubernetes/d/service.html

**Comment by aareet** [comment]
Please reopen if this is still an issue.
