### ISSUE TITLE
Deployment update checks replicationcontroller instead of rollout status

### ISSUE THREAD

**Issue by enozero** [terraform-providers/terraform-provider-kubernetes#210]
### Terraform Version
0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- deployment

### Debug Output
https://gist.github.com/enozero/9e60d362b7801b779555133241608059

### Expected Behavior
It should check the status of the deployment rollout.

### Actual Behavior
It check the replicationcontroller, which is not created

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by enozero** [comment]
More details here: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/101#issuecomment-437148157

**Comment by enozero** [comment]
I've verified locally changing the function call to `waitForDeploymentReplicasFunc` works perfectly. I'll submit a pull request on it.

**Comment by enozero** [comment]
@alexsomesan for visibility

**Comment by alexsomesan** [comment]
Thanks for documenting this and validation the proposed solution.
I'd love to take a look at that PR.

**Comment by enozero** [comment]
This can be closed out!
