### ISSUE TITLE
ConfigMap Documentation

### ISSUE THREAD

**Issue by charles-d-burton** [terraform-providers/terraform-provider-kubernetes#216]
I think the documentation for the configmap could be a bit better.  The current example is highly simplistic and does not explain how the configmap works with the data.  For instance do the map keys get passed as part of the data?  When I run the following configmap it doesn't work whereas if I run it using kubectl it works fine.  That's largely because it's not clear how to use the configmap and how to format the data that's passed into it.  In the example it's mapping a single value where a configmap can have complex data.

### Terraform Version
v0.11.10

### Affected Resource(s)
kubernetes_config_map

### Terraform Configuration Files
```hcl
resource "kubernetes_config_map" "iam_nodes_config_map" {
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }

  data {
    mapRoles = <<ROLES
|
  - rolearn: ${var.instance_role}
    username: system:node:{{EC2PrivateDNSName}}
    groups:
     - system:bootstrappers
     - system:nodes
    ROLES
}
```

### Expected Behavior
It to apply the configmap to the kubernetes cluster

### Actual Behavior
It applied but didn't seem to work correctly

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I think this is just a documentation thing.  The documentation has an example for a very simple configmap but I can't figure out how to apply a more complex configmap.  It's also not apparent as to how the keys relate to the data.

**Comment by pdecat** [comment]
Have you checked with `kubectl get configmap -n kube-system aws-auth` the actual content of the config map?

It's probably a formatting issue.
Here's a more complex example that I use in some setups:

```
data "template_file" "ip-masq-agent" {
  # Note: the HEREDOC syntax adds a trailing newline that breaks YAML processing for ConfigMap
  template = <<EOF
nonMasqueradeCIDRs:
$${non_masquerade_cidrs}
masqLinkLocal: false
resyncInterval: 60s
EOF

  vars {
    # Do not masquerade for local traffic (local pods CIDR and local subnet CIDR)
    # This allows traffic to other private CIDRs to be accepted
    non_masquerade_cidrs = "${
      join("\n",
        formatlist("  - %s",
            list(var.cluster_cidr),
        )
      )
    }"
  }
}

resource "kubernetes_config_map" "ip-masq-agent" {
  metadata {
    name      = "ip-masq-agent"
    namespace = "${lookup(module.namespaces_system.names_map, "kube-system")}"
  }

  data {
    # Remove trailing newline that breaks YAML processing for ConfigMap
    config = "${chomp(data.template_file.ip-masq-agent.rendered)}"
  }
}
```

**Comment by zakkg3** [comment]
I applied the same aws-auth with the file from the aws documentation, then used your code and imported the configmap. then when i run the plan using "landscape" i get this:

```
~ kubernetes_config_map.iam_nodes_config_map
    data.mapRoles:   -- rolearn: arn:aws:iam::034087141678:role/eks-node-dev
                     -  username: system:node:{{EC2PrivateDNSName}}
                     -  groups:
                     -    - system:bootstrappers
                     -    - system:nodes
                     +  - rolearn: arn:aws:iam::034087141678:role/eks-node-dev
                     +    username: system:node:{{EC2PrivateDNSName}}
                     +    groups:
                     +     - system:bootstrappers
                     +     - system:nodes
```

 makes no sense for me, cant see any difference :D

**Comment by JnMik** [comment]
On this block

```terraform
resource "kubernetes_config_map" "aws_auth_configmap" {

  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }

  data {
    mapRoles = <<YAML
- rolearn: ${aws_iam_role.eks_cluster_iam_role.arn}
  username: system:node:{{EC2PrivateDNSName}}
  groups:
    - system:bootstrappers
    - system:nodes
- rolearn: ${var.bastion_role_arn}
  username: kubectl-access-user
  groups:
    - system:masters
YAML
  }
}
```

I'm having this error

```terraform
Error: Unsupported block type

  on ../modules/eks/kubectl_caller_permission_fix.tf line 17, in resource "kubernetes_config_map" "aws_auth_configmap":
  17:   data {

Blocks of type "data" are not expected here. Did you mean to define argument
"data"? If so, use the equals sign to assign it a value.
```

Could this be a terraform 0.12-rc1 issue ?

**Comment by rastakajakwanna** [comment]
Just in case you end up here (like me) while
1. trying to resolve migration from `terraform-aws-eks` module version which is using local-exec kubectl to new version calling kubernetes module directly
2. tf apply complains about `Error: configmaps "aws-auth" already exists`
3. tf import fails with `Error: Get http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth: dial tcp [::1]:80: connect: connection refused`

Fix:
1. change temporarily your provider to use `load_config_file = true` and `config_path ="your_kubeconf"`
2. tf import <module.terraform-aws-eks.the_kubeconfig_module> kube-config/aws_auth
3. change your temporary provider configuration back to dynamic data
4. apply drift
5. aws eks update-kubeconfig # you know the drill
Problem fixed.
