### ISSUE TITLE
Multiple secret_ref and env_from do not work

### ISSUE THREAD

**Issue by Anthonyzou** [terraform-providers/terraform-provider-kubernetes#225]
### Terraform Version
Terraform v0.11.10
+ provider.kubernetes v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment

### Terraform Configuration Files
```hcl
          env = [{
            name  = "PORT"
            value = "${var.pod_port}"
            }
          ]
          env_from = [{
            secret_ref {
              name = "server"
            }
            secret_ref {
              name = "redis"
            }
          }]
```

### Debug Output
[https://gist.github.com/Anthonyzou/10f620bc8022e6772f5fa146c71c0f82](https://gist.github.com/Anthonyzou/10f620bc8022e6772f5fa146c71c0f82)

### Expected Behavior
Multiple secrets get loaded into the deployment

### Actual Behavior
No deployment

### Steps to Reproduce
1. `terraform apply`

**Comment by Swahjak** [comment]
Also allow usage of both `secret_ref` and `config_map_ref` together.

```yaml
env_from {
  config_map_ref {
    name = "config-map"
  }
  secret_ref {
    name = "secret"
  }
}
```

```txt
Error: Error applying plan:

1 error(s) occurred:

* kubernetes_deployment.frontend_php_fpm_deployment: 1 error(s) occurred:

* kubernetes_deployment.frontend_php_fpm_deployment: Failed to create deployment: Deployment.apps "toppy-webshop-frontend-php-fpm-deployment" is invalid: spec.template.spec.containers[0].envFrom: Invalid value: "": may not have more than one field specified at a time
```

**Comment by Cytram** [comment]
@Swahjak if you define env_from as a list it works.
```
env_from = [{
            config_map_ref {
                name = "ocid-config"
            }
            secret_ref {
                name = "closeio"
}]
```

**Comment by RoryShively** [comment]
I'm running into this issue as well. Is there currently a way to get it working or am I going to have to merge all my config into secrets

**Comment by jrhouston** [comment]
This one has definitely tripped me up a few times. The appropriate terraform practice each is to a define an `env_from` block for each reference you want to make, as `env_from` is itself a list. I can see how how this would be a little surprising if you were using YAML before.

```hcl
env_from {
  secret_ref {
    name = "secret"
  }
}

env_from {
  config_map_ref {
    name = "configmap"
  }
}
```

**Comment by Anthonyzou** [comment]
I just use pulumi now.
