### ISSUE TITLE
import kubernetes_secret causes panic

### ISSUE THREAD

**Issue by zostay** [terraform-providers/terraform-provider-kubernetes#25]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "do_api_key" {
    metadata {
        name = "do-api-key"
    }

    data {
        apiKey = "${var.do_token}"
    }
}
```

### Panic Output
It panicked. I can provide the output if you cannot repro. I am too lazy to read through the crash log to see what/if anything I need to elide.

### Expected Behavior
DON'T PANIC

### Actual Behavior
PANIC

### Steps to Reproduce
1. `terraform import kubernetes_secret.do_api_key do-api-key`

### Important Factoids
I already created the secret do-api-key by running `kubectl create secret generic do-api-key --from-literal=...`, in case that's relevant.

I was messing around with this (while learning terraform and kubernetes) and I tried to do this thinking that importing this value will stop terraform from choking on the already existing token. As it panicked instead, I'll just delete the secret via kubectl and let terraform create it itself.

**Comment by radeksimko** [comment]
Hi @zostay 
thank you for opening this issue.

I'm struggling to reproduce the crash unfortunately. Here's what I tried:

```
$ kubectl create secret generic do-api-key --from-literal=apiKey=blablah
secret "do-api-key" created

$ terraform import kubernetes_secret.do_api_key default/do-api-key
kubernetes_secret.do_api_key: Importing from ID "default/do-api-key"...
kubernetes_secret.do_api_key: Import complete!
  Imported kubernetes_secret (ID: default/do-api-key)
kubernetes_secret.do_api_key: Refreshing state... (ID: default/do-api-key)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Import does not generate configuration, so the next step is to ensure that
the resource configurations match the current (or desired) state of the
imported resources. You can use the output from "terraform plan" to verify that
the configuration is correct and complete.
```

Would you mind providing more details? Removing any sensitive data from the crash/debug log is (obviously) a good practice either way, but in case you want to reduce the risk of exposing any such data here on Github feel free to GPG-encrypt them & send me directly to radek@hashicorp.com. Here's my GPG key: https://keybase.io/radeksimko

**Comment by radeksimko** [comment]
Friendly ping @zostay 

I'd love to fix this as crashes are usually the most annoying bugs, but I can't do so without a repro case, unfortunately. 😢 

To prevent this issue from becoming stale I will close it in 20 days from now if there's no response.
Thanks for the help and understanding.

**Comment by zostay** [comment]
Closing it myself. I can no longer reproduce it and I did not save my logs from before. :(
