### ISSUE TITLE
Feature request: mountOptions

### ISSUE THREAD

**Issue by solita-tvoipio** [terraform-providers/terraform-provider-kubernetes#258]
We are using K8s in Azure (AKS), and have a few Deployments with persistent volumes and volume claims. Before starting to transition the Deployment management to Terraform, we set the mount options using the `volume.beta.kubernetes.io/mount-options` annotation. However, this is deprecated (https://kubernetes.io/docs/concepts/storage/persistent-volumes/), Kubernetes supports setting the mount options directly, and setting the annotations does not work currently in Terraform since they are disallowed as "internal Kubernetes annotation".

My request is, could the `kubernetes_persistent_volume`and `kubernetes_persistent_volume_claim` support setting the mount options directly?

### Terraform Version

Terraform v0.11.11
+ provider.azurerm v1.9.0
+ provider.kubernetes v1.4.0

### Affected Resource(s)

- kubernetes_persistent_volume
- kubernetes_persistent_volume_claim

**Comment by jeff1985** [comment]
I have the same issue. Is there any chance, that this will get solved soon? 
I can't find a way to specify mountOptions when using terraform!
