### ISSUE TITLE
kubernetes_service requires port to be set in situations where kubernetes API doesn't.

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-kubernetes#26]
### Terraform Version
levi@La-Tower:~$ terraform -v
Terraform v0.9.11

### Affected Resource(s)
- kubernetes_service

### Terraform Configuration Files
```hcl
resource "kubernetes_service" "my_external_name" {
  metadata {
    name = "my-external-name"
  }
  spec {
    type = "ExternalName"
    external_name = "google.com"
  }
}
```

### Debug Output
https://gist.github.com/shadycuz/507fbd614b43aacd6a5a46edfbbfc834#file-gistfile1-txt

### Expected Behavior
Service should be created, as described in the kubernetes service [documentation.](https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors)

Extract

> An ExternalName service is a special case of service that does not have selectors. It does not define any ports or endpoints. Rather, it serves as a way to return an alias to an external service residing outside the cluster.
> ```
> kind: Service
> apiVersion: v1
> metadata:
>   name: my-service
>   namespace: prod
> spec:
>   type: ExternalName
>   externalName: my.database.example.com
> ```
> When looking up the host my-service.prod.svc.CLUSTER, the cluster DNS service will return a CNAME record with the value my.database.example.com. Accessing such a service works in the same way as others, with the only difference that the redirection happens at the DNS level and no proxying or forwarding occurs. Should you later decide to move your database into your cluster, you can start its pods, add appropriate selectors or endpoints and change the service type.

### Actual Behavior
Terraform throws an error. 
```
1 error(s) occurred:

* kubernetes_service.my_external_name: "spec.0.port": required field is not set
```
If you set the port, it will then say you need to set target_port

Setting both of these will work, and the service will be created. The service does work as expected...

but I also created a service with out using terraform and ports were not required.

leviisbomb made with terraform forcing me to set the ports.
my-service made manually with out terraform.

![image](https://user-images.githubusercontent.com/17090999/28042773-b8516406-659c-11e7-8d93-af57796d77f9.png)

### Steps to Reproduce
Try to create a Kubernetes Service resource with out defining ports.
1. `terraform apply`

### Important Factoids
port is required per the terraform documentation but it in this case it is not actually required in kubernetes.

**Comment by radeksimko** [comment]
Hi @shadycuz 
thank you for noticing this and reporting it as bug.

I just submitted fix in https://github.com/terraform-providers/terraform-provider-kubernetes/pull/27

**Comment by shadycuz** [comment]
You are welcome @radeksimko 

It seems like a pretty easy fix but sometimes ports are required. Is it up to the user to follow the dependencies from the documenation of that resource? 

If I try to execute a service that requires a port, will terraform error when I run plan or will it allow me to run apply and error when kubernetes rejects it?

just curious. 

Thanks =)

**Comment by radeksimko** [comment]
@shadycuz We don't have any good mechanisms to express conditional requirements (field being `Required` under some conditions) at this point in the core schema, so we just fall back to the API validation there.

The only caveat is that the failure will be raised during `apply`, not `plan`.
