### ISSUE TITLE
kubernetes_stateful_set not updating container image name

### ISSUE THREAD

**Issue by DanielMolander** [terraform-providers/terraform-provider-kubernetes#262]
Hi there,

Creating a kubernetes statefulset works, with the correct image, but updating the image does not use the new image name in the update statement. After updating the image TF recognizes that the container image has changed but repeated apply's will continue to show the recognized change

### Terraform Version
Terraform v0.11.8
+ provider.kubernetes v1.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_stateful_set

### Terraform Configuration Files
```hcl
resource "kubernetes_stateful_set" "stateful_set" {
  metadata {
    name      = "mylabel"
    namespace = "default"

    labels {
      app = "mylabel"
    }
  }

  spec {
    service_name = "mylabel"
    replicas     = "1"

    selector {
      match_labels {
        app = "mylabel"
      }
    }

    template {
      metadata {
        labels {
          app = "mylabel"
        }
      }

      spec {

        container {
          name = "mycontainer"
          image = "image2"
          image_pull_policy = "Always"
        }
      }
    }
  }
}
```

### Debug Output
Note: This is only the end of the output to avoid redacting the entire output
https://gist.github.com/DanielMolander/8d6cc481761317d04707597512baae95

### Expected Behavior
Terraform apply will update the statefulset with the new container image 

### Actual Behavior
Terraform apply recognizes that the container name should be updated, but does not include the change

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. update container image with another valid image
3. `terraform apply`

**Comment by alexsomesan** [comment]
Hi, this is fixed in master, but still unreleased.
Are you able to test with a provider build from master and confirm if it solves your problem?

**Comment by DanielMolander** [comment]
I can confirm this is fixed in master branch, I will close this issue. 
Do you happen to have a plan on when the current master will be released?

and thanks!
