### ISSUE TITLE
RoleBindings are getting recreated on each `terraform plan/apply`

### ISSUE THREAD

**Issue by lainra** [terraform-providers/terraform-provider-kubernetes#283]
Hi there,

### Terraform Version
0.11.8
with terraform-provider-kubernetes v1.5.0
### Affected Resource(s)
- kubernetes_role_binding

### Terraform Configuration Files
```hcl
// Dynamically populated with a list of mail addresses
variable "service_admins" {
  description = "Admins of the microservice"

  type    = "list"
  default = []
}

//local.service_id_with_env is a generated namespace name with environment name suffixed
resource "kubernetes_namespace" "microservice_name_dev" {

  metadata {
    name = "${local.service_id_with_env}"
  }

  provider = "kubernetes.jp-dev"
}

resource "kubernetes_role_binding" "service_admins_is_edit_dev" {
  count    = "${var.enable_kubernetes && (var.service_country == "jp" || var.service_country == "") && var.environment == "dev" ? length(var.service_admins) : 0}"
  provider = "kubernetes.jp-dev"

  role_ref {
    name = "edit"
    kind = "ClusterRole"
  }

  metadata {
    name      = "${replace(var.service_admins[count.index], "/@.*/", "")}-is-edit"
    namespace = "${kubernetes_namespace.microservice_name_dev.metadata.0.name}"
  }

  subject {
    api_group = "rbac.authorization.k8s.io"
    kind      = "User"
    name      = "${var.service_admins[count.index]}"
  }
}
```

### Debug Output
(Small so I will just paste it here)
```
terraform plan -target=kubernetes_role_binding.service_admins_is_edit_jp_dev[5]
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

kubernetes_namespace.microservice_jp_dev: Refreshing state... (ID: redacted-dev)
kubernetes_role_binding.service_admins_is_edit_jp_dev[5]: Refreshing state... (ID: redacted-dev/redacted-is-edit)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ module.redacted-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[5] (new resource required)
      id:                          "redacted-dev/redacted-is-edit" => <computed> (forces new resource)
      metadata.#:                  "1" => "1"
      metadata.0.generation:       "0" => <computed>
      metadata.0.name:             "redacted-is-edit" => "redacted-is-edit"
      metadata.0.namespace:        "redacted-dev" => "redacted-dev"
      metadata.0.resource_version: "174790579" => <computed>
      metadata.0.self_link:        "/apis/rbac.authorization.k8s.io/v1/namespaces/redacted-dev/rolebindings/redacted-is-edit" => <computed>
      metadata.0.uid:              "91bf8832-1ecb-11e9-85ef-42010a920074" => <computed>
      role_ref.%:                  "3" => "2" (forces new resource)
      role_ref.api_group:          "rbac.authorization.k8s.io" => "" (forces new resource)
      role_ref.kind:               "ClusterRole" => "ClusterRole"
      role_ref.name:               "edit" => "edit"
      subject.#:                   "1" => "1"
      subject.0.api_group:         "rbac.authorization.k8s.io" => "rbac.authorization.k8s.io"
      subject.0.kind:              "User" => "User"
      subject.0.name:              "redacted@redacted.com" => "redacted@redacted.com"
      subject.0.namespace:         "" => "default"
```

The RoleBinding already exists in the specified namespace:

```yaml
kg rolebinding redacted-is-edit -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2019-01-23T03:42:56Z
  name: redacted-is-edit
  namespace: redacted-dev
  resourceVersion: "174762708"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/redacted-jp-dev/rolebindings/redacted-is-edit
  uid: f8c832f6-1ec0-11e9-85ef-42010a920074
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: redacted@redacted.com
```

### Expected Behavior
What should have happened?

`terraform plan` should not detect any changes on this resource. (OR at least not require a new resource in that case)

### Actual Behavior

3 points:

Terraform RoleBinding Resource ID:
- As shown above, the id is recomputed every time, even if the final value after computation would be the same as the original value. This is bothersome since it will recreate the resource on each `terraform apply`. (but not breaking)

Under `role_ref`:
- The official plugin set the `role_ref.api_group` to `rbac.authorization.k8s.io` no matter its existing value. As shown above, this change triggers every time a new resource re-creation even when the existing value of `role_ref.api_group` is `rbac.authorization.k8s.io`. Noisy but not breaking.

Under `subject`:
- For `User` objects, the plugin will automatically assign the `namespace` value to `default`, even when unset. This is not a huge trouble, but I wish to ask the implementer why this choice.

Also, adding the  `api_group = "rbac.authorization.k8s.io"` under `role_ref` doesn't have any effect on the issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a resource.tf file with a Namespace, a related RoleBinding with its metadata.name and subject.name as tf variables. (dont know if use of `count` is also a possible bug cause)
2. Create a standard `kubernetes` provider declaration file i.e. provider.tf
3. `terraform init` to download the `kubernetes` plugin
4. `terraform plan`, should show that no resource is existing and the final state with the resource created
5 `terraform apply` should create the `RoleBinding`
6 Doing `terraform plan` a second time should show the same issue as posted above in the `debug output`

### Important Factoids
We were using the forked version of the plugin https://github.com/sl1pm4t/terraform-provider-kubernetes in its 1.2.0 version and built RoleBindings using it.
Now we wish to get back to the official plugin since RBAC is ported here.
However, as shown above, noisy issues are preventing us to do so.
The forked version didn't have this issue at all. (No changes detected)
We wish the official plugin to have the same consistency over same resources.

As of now, it is impossible to use the official plugin since any `terraform plan` and `terraform apply` will make the situation described above.

Could you investigate what is going on, please?

Sincerely,

Raphael

### References

Forked version RBAC documentation reference:
https://github.com/sl1pm4t/terraform-provider-kubernetes/pull/39#issuecomment-410654975

**Comment by dwilliams782** [comment]
Facing the same issue, but it's a common known issue with iterating over lists.

**Comment by lainra** [comment]
HI @alexsomesan, Thank you for your fix https://github.com/terraform-providers/terraform-provider-kubernetes/pull/331/commits/476ddeef7a38be005457d9b0a575f41102e4cafe.

Unfortunately, it doesn't change anything as I get the same output described in the OP.
Terraform wants to strip the `role_ref.api_group` on each execution for existing role_binding resources.

The same behavior occurs whether specifying or not the `role_ref.api_group`:

```
      role_ref.%:                  "3" => "2" (forces new resource)
      role_ref.api_group:          "rbac.authorization.k8s.io" => "" (forces new resource)
      role_ref.kind:               "ClusterRole" => "ClusterRole"
```

**Comment by alexsomesan** [comment]
Hi @lainra!

Please do note that as of v1.5.2 the api_group of role_ref is now a required parameter. This is in accordance with the Kubernetes API which also considers this attribute as required.

If you set this attribute on role_ref you will not get any more differences and the configuration will behave as expected.
I have used your configuration posted in OP to test and can confirm this.

However, there is indeed a second issue here which is that the required nature of api_group is not enforced properly by Terraform itself. This is something I am currently looking into.

Let me know if setting api_group as explained solves your problem.

**Comment by lainra** [comment]
Thank you for you quick reply!
Maybe my last paragraph wasn't clear enough but I tried the 1.5.2 version with 2 different cases:

1. By Specifying 'rbac.authorization.k8s.io' in the Terraform manifest under role_ref block

```
role_ref {
    api_group = "rbac.authorization.k8s.io"
    name = "edit"
    kind = "ClusterRole"
  }
```

2. By not specifying it.

Both cases led to the same issue as posted above. 

Would it be related to the state not being persisted correctly with the role_ref.api_group value? 

I don't know if using a list as generator is part of the issue.

**Comment by lainra** [comment]
@alexsomesan 

Finally, found the issue! 

We were using a custom module to distribute RBAC resources to several folders and it appears that while I edited the former module by adding the role_ref.api_group, it didn't reflect into the sub-folder imported module in $CWD/.terraform/modules/mymodule.

When changing the imported module manifests, I get the expected behavior:

```
  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[0]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[1]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[2]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[3]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[4]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[5]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[6]
      subject.0.namespace:         "" => "default"

  ~ module.kouzoh-echo-jp.kubernetes_role_binding.service_admins_is_edit_jp_dev[7]
      subject.0.namespace:         "" => "default"
```

Then adding `namespace = ""` under `subject` made the trick:

```
resource "kubernetes_role_binding" "service_admins_is_edit_jp_dev" {
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    name = "edit"
    kind = "ClusterRole"
  }

  metadata {
    name      = "${replace(var.service_admins[count.index], "/@.*/", "")}-is-edit"
    namespace = "${kubernetes_namespace.microservice_jp_dev.metadata.0.name}"
  }

  subject {
    api_group = "rbac.authorization.k8s.io"
    kind      = "User"
    name      = "${var.service_admins[count.index]}"
    namespace = ""
  }
}
```
Result:

```
bash-4.4# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.
```

Thank you so much for your support!
