### ISSUE TITLE
Kubernetes provider in CICD Pipeline without kubectl and credentials fails

### ISSUE THREAD

**Issue by marekaf** [terraform-providers/terraform-provider-kubernetes#287]
Hi,
I'm struggling to use kubernetes provider with GKE in gitlab-ci pipeline without kubectl installed.
Works fine on my machine, but not in the pipeline without the kubeconfig context. The docs and examples are always populating token with current kubeconfig context. How do I do that with using the terraform service account and hashicorp/terraform:light docker image? Thanks!

### Terraform Version
```
terraform -v
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
+ provider.helm v0.7.0
+ provider.kubernetes v1.5.0
+ provider.random v2.0.0
+ provider.template v2.0.0
+ provider.tls v1.2.0
```

### Terraform Configuration Files
```hcl

resource "google_container_cluster" "primary" {
  name                     = "prod"
  zone                     = "${var.zone}"
  remove_default_node_pool = true

  min_master_version = "1.10.9-gke.5"

  network = "projects/${var.project}/global/networks/default"
  lifecycle {
    ignore_changes = ["node_pool"]
  }
  node_pool {
    name = "default-pool"
  }
}

provider "helm" {
  tiller_image = "gcr.io/kubernetes-helm/tiller:${var.helm_version}"

  kubernetes {
    host                   = "${google_container_cluster.primary.endpoint}"
    token                  = "${data.google_client_config.current.access_token}"
    client_certificate     = "${base64decode(google_container_cluster.primary.master_auth.0.client_certificate)}"
    client_key             = "${base64decode(google_container_cluster.primary.master_auth.0.client_key)}"
    cluster_ca_certificate = "${base64decode(google_container_cluster.primary.master_auth.0.cluster_ca_certificate)}"
  }
}
```

### Expected Behavior
Kubernetes provider should fetch terraform service account and its token 

### Actual Behavior
```
kubernetes_namespace.dev: Refreshing state... (ID: dev)

Error: Error refreshing state: 1 error(s) occurred:

* kubernetes_namespace.dev: 1 error(s) occurred:

* kubernetes_namespace.dev: kubernetes_namespace.dev: Get http://localhost/api/v1/namespaces/dev: dial tcp [::1]:80: connect: connection refused
```

### Steps to Reproduce
1. `terraform plan`

**Comment by alexsomesan** [comment]
Hi Marek,
We are running the provider in CI with GKE without kubeconfig files.

I will try to reproduce your issue and report back.

**Comment by marekaf** [comment]
great, thanks:))

**Comment by alexsomesan** [comment]
I did notice that you're trying to use the Helm provider in the example you provided.
Was it actually your intention to post this issue in the Kubernetes provider though?

**Comment by paultyng** [comment]
This seems like the upstream progressive apply issue: https://github.com/hashicorp/terraform/issues/4149

You cannot currently (reliably) chain together a provider's config with the output of a resource.
