### ISSUE TITLE
Feature request: {Cluster,""}RoleBinding/{Cluster,""}Role support

### ISSUE THREAD

**Issue by munnerz** [terraform-providers/terraform-provider-kubernetes#30]
It'd be great if we could create ClusterRole, ClusterRoleBinding, Role & RoleBinding resources in a Kubernetes API server.

This is especially so, since Kubernetes only allows privileged users of a Kubernetes cluster create the Cluster* variants of these, making them ideal to be created by something like Terraform.

**Comment by radeksimko** [comment]
Hi @munnerz  
the mentioned resources are currently in v1beta phase: https://kubernetes.io/docs/resources-reference/v1.6/#clusterrole-v1beta1-rbac

As [mentioned](https://github.com/terraform-providers/terraform-provider-kubernetes#contributing-resources) in the Readme, for reasons discussed in https://github.com/terraform-providers/terraform-provider-kubernetes/pull/1#issuecomment-307940033 there are currently no plans on supporting any API that's marked as alpha, beta or generally anything that's not stable/v1.

This may change in the future as we explore ways of dealing with breaking changes on the API's side and reducing the impact on the user.

Thanks for understanding.

**Comment by kbruner** [comment]
RBAC is GA in v1.8.  Any word on when this will be supported?  http://blog.kubernetes.io/2017/10/using-rbac-generally-available-18.html

**Comment by Stelminator** [comment]
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/73 looks to have part of it.

**Comment by nunofernandes** [comment]
Any ideas if ClusterRole will be on the roadmap?

**Comment by RobMaskell** [comment]
The work appears to have been done https://github.com/terraform-providers/terraform-provider-kubernetes/pull/229 it's awaiting review

**Comment by alexsomesan** [comment]
Fully supported in v1.5.1
