### ISSUE TITLE
Feature Request: data source for Secret

### ISSUE THREAD

**Issue by mattysweeps** [terraform-providers/terraform-provider-kubernetes#303]
It would be nice if the Kubernetes provider had a data source for a Kubernetes Secret:
https://kubernetes.io/docs/concepts/configuration/secret/

A Terraform resource already exists:
https://www.terraform.io/docs/providers/kubernetes/r/secret.html

**Comment by alexsomesan** [comment]
Hi Matty,
You'll be glad to hear such a datasource already exists. I think this a problem of the latest documentation not being deployed to the website. I will fix that right away!

In the mean time, you can have a look at the code for the the names of the attributes, if that's helpful.

https://github.com/terraform-providers/terraform-provider-kubernetes/blob/v1.5.0/kubernetes/data_source_kubernetes_secret.go

**Comment by mattysweeps** [comment]
That is good news! Thank you

**Comment by alexsomesan** [comment]
fixed

https://www.terraform.io/docs/providers/kubernetes/d/secret.html
