### ISSUE TITLE
Terraform always wants to change network policy with empty namespace_selector

### ISSUE THREAD

**Issue by RobinsonWM** [terraform-providers/terraform-provider-kubernetes#310]
### Summary
If I write a `kubernetes_network_policy` with an ingress or egress that has an empty `namespace_selector` (i.e. all pods in all namespaces,) Terraform wants to change the resource every time I run `terraform plan` or `terraform apply`, even though it hasn't actually changed.

This happens when a `kubernetes_network_policy` includes something like this:
```hcl
    ingress {
      from {
        namespace_selector {}
      }
      ...
    }
```

Subsequent to creating the resource, every time I run `terraform plan` it wants to change the `namespace_selector` count:
```no-highlight
  ~ kubernetes_network_policy.test
      spec.0.ingress.0.from.0.namespace_selector.#: "0" => "1"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Terraform Version
```
terraform -v
Terraform v0.11.11
+ provider.kubernetes v1.5.0
```

### Affected Resource(s)
- kubernetes_network_policy

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  load_config_file       = false
  host                   = "##REDACTED##"
  token                  = "##REDACTED##"
  cluster_ca_certificate = "##REDACTED##"
  version                = "~> 1.5"
}

resource "kubernetes_network_policy" "test" {
  metadata {
    namespace = "##REDACTED##"
    name      = "test"
  }

  spec {
    policy_types = ["Ingress", "Egress"]

    pod_selector {
      match_labels {
        app = "test"
      }
    }

    ingress {
      ports {
        port     = "443"
        protocol = "TCP"
      }

      from {
        namespace_selector {}
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/RobinsonWM/a173efbb8fdcc3aa42e757115284ae9c

### Panic Output
N/A

### Expected Behavior
Terraform should have reported `No changes. Infrastructure is up-to-date.`

### Actual Behavior
Terraform planned to change the `kubernetes_network_policy` resource:
```no-highlight
Terraform will perform the following actions:

  ~ kubernetes_network_policy.test
      spec.0.ingress.0.from.0.namespace_selector.#: "0" => "1"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Declare a `kubernetes_network_policy` resource with an ingress or egress with an empty `namespace_selector` (i.e. allowing traffic to or from all pods in all namespaces.)
1. `terraform apply` - the initial run creates the network policy as expected
1. `terraform plan` - subsequent runs want to change the resource, even though it has not changed

### Important Factoids
If I query the Kubernetes API for the network policy in question, it does show the empty `namespaceSelector`:
```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2019-02-13T22:41:05Z"
  generation: 1
  name: test
  namespace: ##REDACTED##
  resourceVersion: "8122811"
  selfLink: /apis/extensions/v1beta1/namespaces/##REDACTED##/networkpolicies/test
  uid: 72df809d-2fe0-11e9-808b-4201ac10000a
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app: test
  policyTypes:
  - Ingress
  - Egress
```

**Comment by pdecat** [comment]
As the author of that resource, I'll look into that.

First of all, that's a legitimate use-case: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/05-allow-traffic-from-all-namespaces.md

**Comment by pdecat** [comment]
In the meantime, here is a work-around:

```
resource "kubernetes_network_policy" "test" {
  metadata {
    name      = "test"
    namespace = "default"
  }

  spec {
    pod_selector {
      match_expressions {
        key      = "name"
        operator = "In"
        values   = ["webfront", "api"]
      }
    }

    ingress = [
      {
        ports = [
          {
            port = "http"
          },
          {
            port     = "8125"
            protocol = "UDP"
          },
        ]

        from = [
          {
            namespace_selector {
              match_expressions = []
            }
          },
        ]
      },
    ]

    policy_types = ["Ingress"]
  }
}

provider "kubernetes" {
  version = "1.5.0"
}
```

```
# kubectl get networkpolicies test -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2019-02-14T08:32:22Z"
  generation: 2
  name: test
  namespace: default
  resourceVersion: "1222276"
  selfLink: /apis/extensions/v1beta1/namespaces/default/networkpolicies/test
  uid: 0c8c281f-3033-11e9-bcfa-2012eaee26d6
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: http
      protocol: TCP
    - port: 8125
      protocol: UDP
  podSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - webfront
      - api
  policyTypes:
  - Ingress
```

**Comment by asychev** [comment]
Seems like same problem for me, but with empty pod_selector:

for this **deny-other-namespaces** policy spec

```
pod_selector {}

ingress {
  from {
    pod_selector {}
  }
}
```
got this on every terraform apply:

```
Terraform will perform the following actions:

  ~ kubernetes_network_policy.production_deny_other_ns
      spec.0.ingress.0.from.0.pod_selector.#: "0" => "1"
```

**Comment by pdecat** [comment]
That's the same underlying cause in the metadata flattener code.

The same work-around should apply:

```
            pod_selector {
              match_expressions = []
            }
```

**Comment by asychev** [comment]
@pdecat doesn't work for me, same behaviour

**Comment by pdecat** [comment]
You did put that in the `from` block?

**Comment by asychev** [comment]
@pdecat yes, terraform complain about spec.0.ingress.0.from.0.pod_selector

**Comment by pdecat** [comment]
Oops, I've tested it again and the suggested work-around indeed does not work.
And I did not find any other, sorry. :confused: 

The fix is the same though, I've added this use case to the acceptance tests in my PR #312.
