### ISSUE TITLE
Feature Request: Pod tolerations

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-kubernetes#316]
to tolerate taints

**Comment by mbarrien** [comment]
Duplicate of #294

**Comment by tdmalone** [comment]
^ The above is a PR, and seems to have been closed by its owner without merge. Have pinged the owner to see if it can be re-opened. In the meantime this appears to the only open issue regarding support for tolerations.

**Comment by tdmalone** [comment]
^ There we go, that's the new PR for this.

**Comment by tdmalone** [comment]
Pod tolerations are now available as of [1.8.1](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/CHANGELOG.md#181-july-19-2019), released yesterday.

**Comment by sjmiller609** [comment]
Here is an example, in my case on a tiller deployment.

in the 'spec' block:
```
        dynamic "toleration" {
          for_each = var.tolerations
          content {
            key          = toleration.value["key"]
            operator = toleration.value["operator"]
            value       = toleration.value["value"]
            effect      = toleration.value["effect"]
          }
        }
```
vars file:

```
variable "tiller_tolerations" {
  type        = list(map(string))
  default     = []
  description = "Tolerations to apply to Tiller deployment"
}
```

**Comment by alexsomesan** [comment]
Support for tolerations was introduced in v1.8.1
