### ISSUE TITLE
kubernetes_service port name is required, but in docs optional

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-kubernetes#318]
```
name - (Optional) The name of this port within the service. All ports within the service must have unique names. Optional if only one ServicePort is defined on this service.
```

I don't think it's required in the api?

**Comment by pdecat** [comment]
Hmm, port name is optional in code too: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_service.go#L78

Can you share your configuration of the `kubernetes_service` resource with which you're having an issue and the output of the terraform plan?

**Comment by matti** [comment]
hmm, I think I've had too many terraform errors today; I was hallucinating. sorry.

**Comment by matti** [comment]
nope, here we go, this is not valid without "name" fields @pdecat 

```
* kubernetes_service.nginx: Service "nginx" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]
```

```
resource "kubernetes_service" "nginx" {
  metadata {
    name = "nginx"
  }

  spec {
    selector {
      app = "nginx"
    }

    port {
      name        = "http"
      port        = 80
      target_port = 80
    }

    port {
      name        = "https"
      port        = 443
      target_port = 443
    }

    type = "ClusterIP"
  }
}
```

**Comment by pdecat** [comment]
Ok, it is not terraform that is rejecting this but the kubernetes API.

This happens because there are more than one service port defined:

> The name of this port within the service. This must be a DNS_LABEL. All ports within a ServiceSpec must have unique names. This maps to the 'Name' field in EndpointPort objects. **Optional if only one ServicePort is defined on this service**.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#serviceport-v1-core

**Comment by matti** [comment]
So a resource doc update?

**Comment by pdecat** [comment]
What do you mean? It is already documented.

**Comment by matti** [comment]
ok.
