### ISSUE TITLE
Provider doesn't support resource: kubernetes_cluster_role

### ISSUE THREAD

**Issue by AlexBoulyga** [terraform-providers/terraform-provider-kubernetes#321]
### Terraform Version
Terraform v0.11.11
+ provider.kubernetes v1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_cluster_role

### Terraform Configuration Files
``` main.tf of module
resource "kubernetes_namespace" "monitoring" {
  metadata {
    name = "monitoring"
  }
}

resource "kubernetes_service_account" "prometheus" {
  metadata {
    name = "prometheus"
    labels {
      app= "prometheus-server"
    }
  }
}

resource "kubernetes_cluster_role" "prometheus" {
  metadata {
    name = "prometheus"
  }
  rule {
    api_groups = [""]
    resources = ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs = ["get", "list", "watch"]
  }
  rule {
    api_groups = ["extensions"]
    resources = ["ingresses"]
    verbs = ["get", "list", "watch"]
  }
  rule {
    non_resource_urls = ["/metrics"]
    verbs = ["get"]
  }
}

resource "kubernetes_cluster_role_binding" "prometheus" {
  metadata {
    name = "prometheus"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind = "ClusterRole"
    name = "prometheus"
  }
  subject {
    kind = "ServiceAccount"
    name = "prometheus"
    namespace = "monitoring"
  }
}
```

### Expected Behavior
The kubernetes_cluster_role should exist and work (or throw an error if config is wrong)

### Actual Behavior
Terraform finds the other providers like service account and cluster_role_binding, but does not support cluster_role

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` with the mentioned ressources in a modules main.tf

### Important Factoids
Running on a custom kubernetes cluster on bare metal. But everything else works that i needed besides the cluster_role.

**Comment by Natalique** [comment]
You should be using version = "~> 1.5.1"

**Comment by AlexBoulyga** [comment]
thanks!
