### ISSUE TITLE
Impossible to extract metadata.name from resource kubernetes_secret

### ISSUE THREAD

**Issue by asiragusa** [terraform-providers/terraform-provider-kubernetes#327]
### Terraform Version
Terraform v0.11.10
+ provider.kubernetes v1.5.1

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "test" {
  metadata {
    name = "test"
  }
}

output "test" {
  value = "${kubernetes_secret.test.metadata.name}"
}

output "test2" {
  value = "${kubernetes_secret.test.metadata["name"]}"
}
```

### Debug Output
```
1 error(s) occurred:

* output.test: Resource 'kubernetes_secret.test' does not have attribute 'metadata.name' for variable 'kubernetes_secret.test.metadata.name'

* output.test2: __builtin_StringToInt: strconv.ParseInt: parsing "name": invalid syntax in:

${kubernetes_secret.test.metadata["name"]}
```
### Expected Behavior
I should be able to get the secret name. It's useful to set a dependency on a helm_release that resides in a different module

### Actual Behavior
Error planning changes

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Standard configuration

**Comment by olib963** [comment]
It is actually possible, it's just frustrating because `metadata` is seen as a list. So if you try `.metadata.0.name` it should work fine.

**Comment by asiragusa** [comment]
Thanks for the tip!
