### ISSUE TITLE
Pod Spec: container[].security_context.capabilities missing in Schema

### ISSUE THREAD

**Issue by Preskton** [terraform-providers/terraform-provider-kubernetes#340]
### Terraform Version

```
Terraform v0.11.10
+ provider.kubernetes v1.5.1
```

Observed on `master` at https://github.com/terraform-providers/terraform-provider-kubernetes/blob/fdd717a3a4391d09db0b6555ba0bd35d74abf3c1/kubernetes/schema_pod_spec.go#L128.

### Affected Resource(s)

Any resource that leverages the pod spec (`schema_pod_spec.go`).

### Expected Behavior

The `capabilities` map should be supported and applied to the resulting container spec.

Per the documentation at https://www.terraform.io/docs/providers/kubernetes/r/daemonset.html#security_context it appears `capabilities` should be supported.

It also seems `capabilities` is handled as part of `structures_container.go`: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/c0f2cdf5f603f623c346caf2cf91b4d88e3035bb/kubernetes/structures_container.go#L25 It may have been an oversight when setting up the `Schema`.

### Actual Behavior

Within a pod spec's `container[x].security_context` definition, when you try to use the `capabilities` to `add` or `drop` capabilities, like so:

```hcl
            "security_context" = {
              "capabilities" = {
                "add" = ["NET_ADMIN"]
              }
            }
```

Terraform complains with an error message like:

```
Error: module.kubernetes_base_provisioning.module.dns_mapper.kubernetes_daemonset.daemonset: spec.0.template.0.spec.0.container.0: invalid or unknown key: capabilities
```

### Steps to Reproduce

1. Attempt to `apply` any resource using `security_context.capabilities`

**Comment by RobinsonWM** [comment]
I'm on the same version as you and not able to repro.  I have been using `capabilities` for some time.

It might help to see a more complete example of your HCL.  The error message doesn't appear to be complaining about the snippet you pasted.  The error message seems to suggest that you might have a second `capabilities` declared _outside of_ `security_context`.

**Comment by Preskton** [comment]
@RobinsonWM always helps to have a second set of eyes. My mistake - typo! :)
