### ISSUE TITLE
deployment knob for automount_service_account_token

### ISSUE THREAD

**Issue by dolvany** [terraform-providers/terraform-provider-kubernetes#364]
It seems that automount_service_account_token defaults to false on a deployment with no knob to change it. Doesn't this render the same knob useless on a service account since the deployment setting takes precedence? Is there a compelling reason that this knob does not exist for a deployment?

**Comment by mbarrien** [comment]
See response in https://github.com/terraform-providers/terraform-provider-kubernetes/issues/38#issuecomment-318581203 to explain reasoning for this and workaround.

**Comment by dolvany** [comment]
I see the explanation is referencing the default service account which is not my use case, but the reasoning isn't entirely clear. Something about ambiguity, it seems. Adding a blurb to the deployment documentation may reduce the issue volume surrounding this feature omission. Otherwise, peeps are left to assume that this is a bug or oversight. Something such as automount_service_account_token (not implemented) with reasoning and a link to the workaround.

**Comment by tdmalone** [comment]
I was just about to create an issue about this too, after debugging it and realising what was happening.

This definitely needs to be in the documentation. @dolvany Would you be open to reopening this issue (to assist in discovery / a pointer to update the documentation)?
