### ISSUE TITLE
Error when patching annotation with a "/"

### ISSUE THREAD

**Issue by tdegiacinto** [terraform-providers/terraform-provider-kubernetes#37]
When using annotation containing a "/", every terraform's run (except the first one which will create the resource), will try to update the resource and failed with the following error.
````
jsonpatch add operation does not apply: doc is missing path: /metadata/annotations/service.beta.kubernetes.io/aws-load-balancer-backend-protocol
````
### Terraform Version
0.9.11

### Affected Resource(s)
- kubernetes_service
- I guess all resources using patch

### Terraform Configuration Files
```hcl
resource "kubernetes_service" "test" {
  metadata {
    name      = "service-test"
    namespace = "test"

    annotations {
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol" = "tcp"
    }
  }

  spec {
    selector {
      App = "App1"
    }

    port {
      port        = 443
      target_port = 443
    }

    type = "LoadBalancer"
  }
}
```

### Debug Output

This is due to the fact we use json format when we make the patch call.
Indeed with the json format we have to give a path like this 
```
"path":"/metadata/annotations/some_annotation"
```
however when the annotation have a slash it will be interpreted as a suffix path.
````
annotation_name = service.beta.kubernetes.io/aws-load-balancer-backend-protocol
"path":"/metadata/annotations/service.beta.kubernetes.io/aws-load-balancer-backend-protocol"
````

### Steps to Reproduce
Launch terraform two times. Once for creating the resource the other one for getting the error.
1. `terraform apply`

### Suggestion

I Guess we should use "StrategicMergePatchType" instead of "JSONPatchType"

Quick test I made
````
kubectl patch service confmgr-foreman --type='json' -p='[{"path":"/metadata/annotations/service.beta.kubernetes.io/aws-load-balancer-backend-protocol","value":"tcp","op":"add"}]'
Error from server: jsonpatch add operation does not apply: doc is missing path: /metadata/annotations/service.beta.kubernetes.io/aws-load-balancer-backend-protocol

kubectl patch service confmgr-foreman -p='{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-backend-protocol":"tcp"}}}'
service "confmgr-foreman" patched
````

**Comment by radeksimko** [comment]
Hi @tdegiacinto,
thank you for reporting this bug.

Just to explain the context here - #40 fixed a bug preventing users from updating annotations with slashes. That was already shipped in the last release and makes such annotations work w/out issues. That said we don't support k8s internal annotations (parse-able URN with hostname `kubernetes.io`) for reasons mentioned in #50 which is also adding explicit validation, so your attached config won't work for that reason.

I hope it makes sense - let me know if it doesn't or if you have more questions about it.
