### ISSUE TITLE
Kubernetes provider gives error on first 'terraform apply'

### ISSUE THREAD

**Issue by mukesh-panigrahi** [terraform-providers/terraform-provider-kubernetes#382]
Hello,

Stuck with a issue on kubernetes provider.
Getting below error on first 'terraform apply'.
Everything do works perfectly fine on subsequent tf apply.
Can anyone help me to find out the reason for this.
I am working on something where I need to automate everything in my pipeline and should not fail in between like this.
```
*kubernetes_service.memcache: Post http://localhost/api/v1/namespaces/default/services: dial tcp 127.0.0.1:80: connect: connection refused

* kubernetes_deployment.memcached: Failed to create deployment: Post http://localhost/apis/apps/v1/namespaces/default/deployments: dial tcp 127.0.0.1:80: connect: connection refused
```
### Terraform Version
Terraform v0.11.11
+ provider.google v2.0.0
+ provider.kubernetes v1.5.2

### Affected Resource(s)
Any GKE resource I try to create using the provider.

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_path = "${path.root}/generated/kubeconfig"
  config_context_auth_info = "target-cluster"
}
```
### Expected Behavior
It should worked on the very first time itself, instead of me manually doing a 'terraform apply' again.

### More info to my case:
I am creating the kubeconfig file to a specified path using local_file resource and referring the same in my provider.

**Comment by alexsomesan** [comment]
This looks like wrong / missing credentials.
How are you configuring credentials for the provider.
Is there any `$HOME/.kube/config` file present?

**Comment by mukesh-panigrahi** [comment]
Well i am providing it using a generated local-file resource.
I had to giveup with the config file method as their were to many dependency and default options to be taken care of.
I used the token method, which worked fine.

**Comment by paultyng** [comment]
This seems like the upstream progressive apply issue: https://github.com/hashicorp/terraform/issues/4149

You cannot currently chain together a provider's config with the output of a resource.

**Comment by ddska** [comment]
@mukesh-panigrahi 
> I used the token method, which worked fine.

Could you describe this "token method" please? I have the same issue.

**Comment by HanBingfeng** [comment]
Could you describe token method more specifier, what should i do if i use token method to cert provider

**Comment by ddska** [comment]
@HanBingfeng 
Here is the example of using token auth:
```
data "google_client_config" "default" {}

data "google_container_cluster" "mycluster" {
  name = "mycluster"
  location = var.region
}

provider "kubernetes" {
  load_config_file = false
  host = google_container_cluster.mycluster.endpoint
  token = data.google_client_config.default.access_token

  client_certificate = base64decode(google_container_cluster.mycluster.master_auth[0].client_certificate)
  client_key = base64decode(google_container_cluster.mycluster.master_auth[0].client_key)
  cluster_ca_certificate = base64decode(google_container_cluster.mycluster.master_auth[0].cluster_ca_certificate)
}
```

**Comment by HanBingfeng** [comment]
@ddska thank you for your reply    : )
