### ISSUE TITLE
The working_dir parameter is not working

### ISSUE THREAD

**Issue by conet** [terraform-providers/terraform-provider-kubernetes#397]
Even though I add `working_dir` the resulting kubernetes resource does not have the `workingDir` field set. Probably because it's missing in the `expandContainers` function in `structures_container.go`

**Comment by alexsomesan** [comment]
Thanks for reporting this, Cristian.
I will fix this in the next couple of days.

**Comment by TylerWanner** [comment]
Still seeing this occurring
