### ISSUE TITLE
kubernetes_deployment not creating services on the AKS cluster

### ISSUE THREAD

**Issue by swathiAMD** [terraform-providers/terraform-provider-kubernetes#416]
Hi,

  Trying to run an  terraform script for Azure rm. The script is combination of Application gateway , AKS , vnet and subnet. Also I am trying to do deploy the atlassian-confluence on the AKS in the same script.

Below is the code for the deployment using Kubernetes provider:

provider kubernetes {

  host = "${azurerm_kubernetes_cluster.kubernetes.kube_config.0.host}"
  #username = "${azurerm_kubernetes_cluster.kubernetes.kube_config.0.username}"
  #password = "${azurerm_kubernetes_cluster.kubernetes.kube_config.0.password}"

  client_certificate     = "${base64decode(azurerm_kubernetes_cluster.kubernetes.kube_config.0.client_certificate)}"
  client_key             = "${base64decode(azurerm_kubernetes_cluster.kubernetes.kube_config.0.client_key)}"
  cluster_ca_certificate = "${base64decode(azurerm_kubernetes_cluster.kubernetes.kube_config.0.cluster_ca_certificate)}"
}

resource "kubernetes_service_account" "default" {
  automount_service_account_token = true
  metadata {
    name = "serviceaccountname"
  }
}resource "kubernetes_deployment" "confluence"{
  metadata {
    name = "atlassian-confluence"
    labels = "${local.confluence_labels}"
  }

  spec {
    replicas = 3

    selector {
      match_labels = "${local.confluence_labels}"
    }

    template {
      metadata {
        labels = "${local.confluence_labels}"
      }

      spec {

        container {
          name = "atlassian-confluence"
          image = "cptactionhank/atlassian-confluence:latest"
          volume_mount {
            mount_path = "/var/run/secrets/kubernetes.io/serviceaccount"
            name = "${kubernetes_service_account.default.default_secret_name}"
            read_only = "true"

          }
          #port {
          #  container_port = 80
          #  host_port = 80
          #}

          env {
            name = "atlassian-confluence"
            value = "latest"
          }

        }
        volume {
          name = "${kubernetes_service_account.default.default_secret_name}"
          secret {
            secret_name = "${kubernetes_service_account.default.default_secret_name}"
            default_mode = "0420"

          }

        }

        restart_policy = "Always"
        termination_grace_period_seconds = 30
        dns_policy = "ClusterFirst"
        service_account_name = "default"

      }
    }
  }

}

The terraform build is successful and all the resources are created correctly. But when I launch the dashboard for the AKS cluster created from my script. I can see the above pod created  i.e pods section has 3 confluence shown , but in the services section i cant view this pod as service.
I m not sure if i m missing something.

PS: I m new to Terraform concept.

Thanks,
Swathi S

**Comment by rsalmond** [comment]
Hey @swathiAMD, you need to define a kubernetes service object to point requests to your deployment. You can do so with the [kubernetes_service](https://www.terraform.io/docs/providers/kubernetes/r/service.html) terraform resource.

**Comment by swathiAMD** [comment]
> Hey @swathiAMD, you need to define a kubernetes service object to point requests to your deployment. You can do so with the [kubernetes_service](https://www.terraform.io/docs/providers/kubernetes/r/service.html) terraform resource.

@rsalmond  thnaks for your reply...I have added the kubernetes service object :)
