### ISSUE TITLE
Template spec restart_policy unsupported value "Never"

### ISSUE THREAD

**Issue by samling** [terraform-providers/terraform-provider-kubernetes#435]
### Terraform Version
v0.12.0-beta2
Kubernetes Provider v1.6.2

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "kubernetes_deployment" "elasticsearch-init" {
  metadata {
    name = "elasticsearch-init"
    labels = {
      App = "elasticsearch-init"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        App = "elasticsearch-init"
      }
    }

    template {
      metadata {
        labels = {
          App = "elasticsearch-init"
        }
      }

      spec {
        container {
          image = "elasticsearch-init"
          name  = "elasticsearch-init"
          image_pull_policy = "Never"
        }

        restart_policy = "Never"
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/samling/dbcf20928fc6be1b43c7b704007a23e1

### Expected Behavior
A deployment should be created with a restartPolicy of "Never".

### Actual Behavior
The deployment fails to be created and describes only one valid restartPolicy.

### Steps to Reproduce
1. Create a main.tf file with a `kubernetes_deployment` resource matching the above configuration file (any valid container image will work).
2. Specify a `restart_policy` of `Never` or `OnFailure` under the template spec block.
3. Attempt to execute the terraform plan with `terraform apply`.

### Important Factoids
* We are using the latest terraform 0.12.0 beta and associated Kubernetes beta provider, if that affects anything.
* The [documentation](https://www.terraform.io/docs/providers/kubernetes/r/deployment.html#restart_policy) lists "OnFailure" and "Never" as valid values. The [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) also lists those three values.

### References
I could find no other references to this issue.

**Comment by pdecat** [comment]
Hi @samling, that message is returned by the API server: 

> Pod Template
> [...]
> Only a `.spec.template.spec.restartPolicy` equal to `Always` is allowed, which is the default if not specified.

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template

**Comment by pdecat** [comment]
The provider documentation for workload controllers needs to be fixed:

> - Use a `Job` for Pods that are expected to terminate, for example, batch computations. Jobs are appropriate only for Pods with `restartPolicy` equal to `OnFailure` or `Never`.
> - Use a `ReplicationController`, `ReplicaSet`, or `Deployment` for Pods that are not expected to terminate, for example, web servers. ReplicationControllers are appropriate only for Pods with a `restartPolicy` of `Always`.

**Comment by samling** [comment]
Thanks @pdecat, that makes sense. Is there any plan for the official provider to support jobs (even though they're somewhat at odds with the stateful nature of terraform)? Or else is there some recommended way to handle use cases like this within the capabilities of the provider?

**Comment by pdecat** [comment]
Job is tracked by https://github.com/terraform-providers/terraform-provider-kubernetes/issues/86
CronJob by https://github.com/terraform-providers/terraform-provider-kubernetes/issues/212

And there's a PR in progress for both: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/411

**Comment by samling** [comment]
Thanks again @pdecat. I'll close this.
