### ISSUE TITLE
Incorrect selector key in example usage of service

### ISSUE THREAD

**Issue by kmalachowski** [terraform-providers/terraform-provider-kubernetes#47]
Hi,
In website/docs/r/service.html.markdown there is incorrect selector key.
It should be app not App.

```
resource "kubernetes_service" "example" {
  metadata {
    name = "terraform-example"
  }
  spec {
    selector {
      ===>app<=== "MyApp"

    }
    session_affinity = "ClientIP"
    port {
      port = 8080
      target_port = 80
    }

    type = "LoadBalancer"
  }
}
```

Thanks.

**Comment by radeksimko** [comment]
Hi @kmalachowski 
thanks for opening the issue and sorry for any confusion caused.

Do you mind explaining why is it incorrect or in what context is it incorrect? The example assumes pods with the given selector - would adding an example of matching `kubernetes_pod` help?

**Comment by kmalachowski** [comment]
Radek, 
Sorry it was a mental leap:)
It's not incorrect in terms of label's definition,
but It may be confusing for someone who follows kubernetes documentation, because they always use lower case letters.

In my case, k8 deployment is separated from terraform(it is part of CI/CD pipeline), and has "app=MyApp" selector accroding to kubernetes docs convetion.

In terraform, I've setup only gke_cluster and kuberentes service.

It wasn't working together, finally I figured it out, that in terraform part I have App=MyApp selector. 

In my opinion terraforms examples should be changed to follow kuberentes docs, because it may save devs time on debugging.  But it is only my opinion:)
Thanks

**Comment by radeksimko** [comment]
Understood, thanks for the clarification.
