### ISSUE TITLE
lifecycle ignore_changes does not work with 0.12

### ISSUE THREAD

**Issue by umglurf** [terraform-providers/terraform-provider-kubernetes#473]
### Terraform Version
Terraform v0.12.0
+ provider.kubernetes v1.7.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment
- kubernetes_stateful_set

### Terraform Configuration Files

Version 0.11 config:

```hcl
provider "kubernetes" {
}

resource "kubernetes_deployment" "test" {
  metadata {
    name = "test"
    namespace = "default"
    
    labels {
      app = "test"
    }
  }

  spec {
    selector {
      match_labels {
        app = "test"
      }
    }
    template {
      metadata {
        labels { 
          app = "test"
        }
      }
      spec {
        container {
          name = "test"
          image = "alpine"
        }
      }
    }
  }

  lifecycle {
    ignore_changes = ["spec.0.template.0.spec.0.container.0.image"]
  }
}
```

Version 0.12 config:
```hcl
provider "kubernetes" {
}

resource "kubernetes_deployment" "test" {
  metadata {
    name      = "test"
    namespace = "default"

    labels = {
      app = "test"
    }
  }

  spec {
    selector {
      match_labels = {
        app = "test"
      }
    }
    template {
      metadata {
        labels = {
          app = "test"
        }
      }
      spec {
        container {
          name  = "test"
          image = "alpine"
        }
      }
    }
  }

  lifecycle {
    ignore_changes = [spec[0].template[0].spec[0].container[0].image]
  }
}
```

### Debug Output
https://gist.github.com/umglurf/220a329cee787105b696534e42602fc5

### Expected Behavior
The container image change is ignored

### Actual Behavior
In terraform 0.12 it always want to change back the container image

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change image for container
1. `terraform apply`

### Important Factoids
Kubernetes 14.2

**Comment by sbrandtb** [comment]
Is this a duplicate of #21433?

**Comment by umglurf** [comment]
Yes, it seems so

**Comment by umglurf** [comment]
The referenced bug has been fixed and the is part of 0.12.3. I've tested with 0.12.3, but it does not work for the kubernetes provider. Is there something that must be updated in this provider as well to make this work?

**Comment by umglurf** [comment]
Tested with 0.12.4 and the issue is resolved there

**Comment by kawsark** [comment]
Hello @umglurf, can you post the specific syntax you used for ignore_changes?

**Comment by umglurf** [comment]
Hi, both of these syntaxes works now

  lifecycle {
    ignore_changes = [
      spec.0.template.0.spec.0.container.0.image
    ]
  }
  lifecycle {
    ignore_changes = [
      spec[0].template[0].spec[0].container[0].image
    ]
  }

**Comment by kawsark** [comment]
Thank you @umglurf ! I am having an issue in specifying `ignore_changes` for annotations with the Kubernetes provider in 0.12. I am wondering if you ran into this issue as well. 

I tried specifying `metadata[0].annotations["openshift.io/sa.scc.supplemental-groups"]`. This does not result a syntax error, however, it doesn't actually ignore these annotations during runtime (during each plan/apply terraform wants to set them to empty). 

Specifying `metadata[0].annotations.openshift.io/sa.scc.supplemental-groups.` results a syntax error.

Here is my `main.tf` file:
```
resource "kubernetes_namespace" "kawsar-tf-project" {
  metadata {
    annotations = {
      "therealk.com/type" = "terraform"
      "therealk.com/name" = "project"
    }
    labels = {
      type = "terraform"
    }
    name = "kawsar-tf-project"
  }

  lifecycle {
      ignore_changes = [
        metadata[0].annotations["openshift.io/sa.scc.supplemental-groups"],
        metadata[0].annotations["openshift.io/sa.scc.uid-range"],
        metadata[0].annotations["openshift.io/sa.scc.mcs"]
      ]
  }
}
```
terraform plan snippet:
```
      ~ metadata {
          ~ annotations      = {
              - "openshift.io/sa.scc.mcs"                 = "s0:c9,c4,c100" -> null
              - "openshift.io/sa.scc.supplemental-groups" = "1000110000/10000" -> null
              - "openshift.io/sa.scc.uid-range"           = "1000110000/10000" -> null
                "therealk.com/name"                       = "project"
                "therealk.com/type"                       = "terraform"
             }
```

**Comment by umglurf** [comment]
Hi

The documentation says:
ou can also ignore specific map elements by writing references like tags["Name"] in the ignore_changes list, though with an important caveat: the ignoring applies only to in-place updates to an existing key. Adding or removing a key is treated by Terraform as a change to the containing map itself rather than to the individual key, and so if you wish to ignore changes to a particular tag made by an external system you must ensure that the Terraform configuration creates a placeholder element for that tag name so that the external system changes will be understood as an in-place edit of that key

I've tested and if you add the annotations in your resources with dummy values, the ignore works:

resource "kubernetes_namespace" "kawsar-tf-project" {
  metadata {
    annotations = {
      "therealk.com/type" = "terraform"
      "therealk.com/name" = "project"
      "openshift.io/sa.scc.supplemental-groups" = "dummy"
      "openshift.io/sa.scc.uid-range" = "dummy"
      "openshift.io/sa.scc.mcs" = "dummy"
    }
    labels = {
      type = "terraform"
    }
    name = "kawsar-tf-project"
  }

  lifecycle {
      ignore_changes = [
        metadata[0].annotations["openshift.io/sa.scc.supplemental-groups"],
        metadata[0].annotations["openshift.io/sa.scc.uid-range"],
        metadata[0].annotations["openshift.io/sa.scc.mcs"]
      ]
  }
}

**Comment by kawsark** [comment]
Thank you @umglurf !! That worked great, I appreciate the fast response. I came across this documentation but wasn't sure how it applied to nested elements (i.e. metadata > annotations > key vs. tags > key). Thanks again for the clarification!

**Comment by ziporah** [comment]
This issue is not fixed, your workaround only works if you apply the dummy parameters after the namespace is created.
If you recreate the namespace, it will get created with the dummy parameters, rendering openshift useless, since the parameters are required for applying the pod security policy:
```
11:07 $ oc get project testproject  -o yaml
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/sa.scc.mcs: dummy
    openshift.io/sa.scc.supplemental-groups: dummy
    openshift.io/sa.scc.uid-range: dummy
  creationTimestamp: 2019-08-27T08:53:12Z
  deletionTimestamp: 2019-08-27T09:07:45Z
  name: testproject
  resourceVersion: "..."
  selfLink: /apis/project.openshift.io/v1/projects/testproject
  uid: 1a06d9aa-c8a8-11e9-9c62-005056ab74a5
spec:
  finalizers:
  - kubernetes
```

With this config you will end up with 
```
failed to list pods ... User .... is forbidden: no providers available to validate pod request.
```
Comment the 3 openshift lines, run terraform plan / apply, and you're back up with the namespace and deployment. Before the second run, you need to remove the comments again or your security context and uid-ranges will alter on every plan/deploy cycle.

**Comment by umglurf** [comment]
Hi @ziporah 
I would say this issue is resolved, the original problem is fixed. The ignore of the annotations works as documented, to get the desired behaviour you need to file a issue in terraform core to support ignoring individual items in a map for lifecycle ignore.
