### ISSUE TITLE
kubernetes_secret dockerconfigjson does not work with Terraform v0.12

### ISSUE THREAD

**Issue by paulashbourne** [terraform-providers/terraform-provider-kubernetes#476]
In Terraform v0.12, we can no longer create dockerconfig Kubernetes secrets using the format described in the official docs (https://www.terraform.io/docs/providers/kubernetes/r/secret.html)

The issue is that the `kubernetes_secret` resource expects `data` to contain a key `.dockerconfigjson`. In Terraform `v0.11.x`, this was not an issue because the arguments to `data` could be quoted. However, in `v0.12.0`, quotes are not allowed on the arguments, and arguments cannot begin with the `.` character. 

### Terraform Version
`terraform v0.12`

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "quay" {
  type = "kubernetes.io/dockerconfigjson"
  metadata {
    name = "quay"
  }

  data {
    ".dockerconfigjson" = "<filtered>"
  }
}
```

### Expected Behavior
Configuration should be valid.

### Actual Behavior
Terraform outputs the following error when I run `terraform workspace <workspace name>` or `terraform plan`:
```
Error: Invalid argument name

  on secrets.tf line 16, in resource "kubernetes_secret" "quay":
  16:     ".dockerconfigjson" = "${data.aws_s3_bucket_object.quay_config.body}"

Argument names must not be quoted.
```

### Steps to Reproduce
1. Create a `kubernetes_secret` resource for a docker config using the format described on https://www.terraform.io/docs/providers/kubernetes/r/secret.html
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @paulashbourne,

It looks like you may have missed running the `0.12upgrade` tool from the [upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html) This should have re-written the `data` field to use the correct argument syntax, and left the quoted keys in place:

```
resource "kubernetes_secret" "quay" {
  type = "kubernetes.io/dockerconfigjson"
  metadata {
    name = "quay"
  }

  data = {
    ".dockerconfigjson" = "<filtered>"
  }
}
```

**Comment by paulashbourne** [comment]
Hi @jbardin I did use the `0.12upgrade` tool and it reported no issues. However, after reading your message and updating `data` to add the `=`, this works.

Thanks for your help.
