### ISSUE TITLE
Provider 1.7.0 cannot set automountserviceaccounttoken=true in deployment descriptor

### ISSUE THREAD

**Issue by rbock44** [terraform-providers/terraform-provider-kubernetes#482]
using the provider 1.7.0 and terraform 0.11.14 I am facing a problem that now my incress controller no longer has a serviceaccount token mounted.

As far as I know the automountServiceAccountToken=true is possible in the template spec for the pod. After I changed the deployment yaml in kubernetes directly to true using kubectl it was mounting the token and worked fined.

Terraform plan was not detecting the change I did, so I guess the feature is not set by the provider.

Specifying the automount_service_account_token = true in service account was not working.

We did not upgrade our cluster which is Kubernetes 12.

Best regards

Richard

**Comment by alexsomesan** [comment]
Support for setting `automountServiceAccountToken` is missing in Pod and Pod Template spec.
There is a PR in progress to resolve this: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/261

**Comment by rbock44** [comment]
Thaks
