### ISSUE TITLE
kubernetes deployment spec.0.template.0.spec.0.container.0.args.0 must be a single value, not a map

### ISSUE THREAD

**Issue by fizzamahdi** [terraform-providers/terraform-provider-kubernetes#490]
### Terraform Version
Terraform v0.11.10

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "table-manager" {

  "metadata" {
    name = "table-manager"
    namespace = "monitoring"
  }

  "spec" {
    replicas = 1

    template {
      metadata {
        annotations {
          "iam.amazonaws.com/role" = "${aws_iam_role.cortex_role.id}"
        }
        labels {
          name = "table-manager"
        }
      }

      spec {
        container {
          image = "quay.io/cortexproject/table-manager"
          name  = "table-manager"
          image_pull_policy = "IfNotPresent"
          args {
            server.http-listen-port = 80
            dynamodb.original-table-name = "${aws_dynamodb_table.cortex_table.name}"
          }
          port {
            container_port = 80
          }
        }
      }
    }
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
`terraform plan` should produce a plan

### Actual Behavior
`terraform plan` errors out with:
"kubernetes_deployment.table-manager: spec.0.template.0.spec.0.container.0.args.0 must be a single value, not a map"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by pdecat** [comment]
Hi, it's supposed to be defined as a list like this:

```
          args  = ["/bin/sh", "-c", "touch /tmp/healthy; sleep 300; rm -rf /tmp/healthy; sleep 600"]
```
