### ISSUE TITLE
Statefulset + deployment - change of env variables forces new resource.

### ISSUE THREAD

**Issue by jaceq** [terraform-providers/terraform-provider-kubernetes#492]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12 and also 0.11
kubernetes-provider 1.7.0

### Affected Resource(s)
kubernetes_statefulset
kubernetes_deployment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
When I make changes to env variables I expect this to be in-place update. 
When I make changes via UI in Kubernetes (in yaml template) then changes to env variables are in place (and pods are re-started according to update strategy.

### Actual Behavior
When I make changes to env variables for one of those resources my workload is re-created and causing a downtime.

Example output:
```
 - env { # forces replacement
  - name  = "n2" -> null
  - value = "v2" -> null # forces replacement
}
```

### Steps to Reproduce
1. Deploy any statefulset and / or deployment
2. Change / add / remove any env variable from it.

**Comment by pdecat** [comment]
Same as https://github.com/terraform-providers/terraform-provider-kubernetes/issues/201

**Comment by jaceq** [comment]
I will close this issue given there is already #201 as per @pdecat
