### ISSUE TITLE
Not honoring kube-config for provisioning tiller on first run

### ISSUE THREAD

**Issue by nitrag** [terraform-providers/terraform-provider-kubernetes#494]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.7

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_service_account

### Terraform Configuration Files
```hcl
resource "null_resource" "configure-kubectl-local" {

  provisioner "local-exec" {
    command = <<EOT
      aws eks update-kubeconfig --name ${var.cluster_name} --region ${var.aws_region} --kubeconfig .kube-config.yaml;
   EOT
  }
  depends_on = [
    "aws_eks_cluster.kube-cluster",
    "aws_autoscaling_group.kubedeploy"
  ]
}

provider "kubernetes" {
  version = "~> 1.7"
  config_path = "./.kube-config.yaml"
}

resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }

  automount_service_account_token = true

  depends_on = [
    "aws_eks_cluster.kube-cluster",
    "null_resource.apply-auth-config-map",
    "null_resource.configure-kubectl-local"
  ]
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    kind      = "ClusterRole"
    name      = "cluster-admin"
    api_group = "rbac.authorization.k8s.io"
  }

  subject {
    kind = "ServiceAccount"
    name = "tiller"

    api_group = ""
    namespace = "kube-system"
  }

  depends_on = ["kubernetes_service_account.tiller"]
}
```

### Debug Output
https://gist.github.com/nitrag/59991d5520f55f61a46e212c8af507ac

### Expected Behavior
I'm expecting the kubernetes provider to pickup the KUBECONFIG (`kubernetes.config_path`) that is generated after my k8s cluster is created. My goal is to run `terraform apply` and have it spin up cluster, provision kubernetes, and install helm charts all in one run.

### Actual Behavior
It's not honoring/finding the local KUBECONFIG file and trying to connect to a localhost kubernetes cluster. **I imagine the kubernetes provider is trying to load the file from `config_path` at the start of `terraform apply` instead of on-the-fly** because it fails the first time and I run `terraform apply` a second time and it works instantly the second time.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Get `Error: Post http://localhost/api/v1/namespaces/kube-system/serviceaccounts: dial tcp 127.0.0.1:80: connect: connection refused`
3. `terraform apply`

### Important Factoids
AWS EKS

**Comment by nitrag** [comment]
I tried changing `load_config_file = false` but that simply ignores the config path entirely. I think the proper behavior should be to source the KUBECONFIG the first time a resource is called/required.

**Comment by nitrag** [comment]
Reason I'm struggling here is I can't seem to install Tiller on the first go. I have to run `terraform apply twice`.

```
aws_eks_cluster.kube-cluster: Still creating... [7m10s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [7m20s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [7m30s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [7m40s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [7m50s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m0s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m10s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m20s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m30s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m40s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [8m50s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [9m0s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [9m10s elapsed]
aws_eks_cluster.kube-cluster: Still creating... [9m20s elapsed]
aws_eks_cluster.kube-cluster: Creation complete after 9m25s [id=terraform-eks-demo15]
data.aws_ami.eks-worker: Refreshing state...
aws_launch_configuration.kubedeploy: Creating...
aws_launch_configuration.kubedeploy: Creation complete after 4s [id=terraform-eks-demo1520190607135533997000000006]
aws_autoscaling_group.kubedeploy: Creating...
aws_autoscaling_group.kubedeploy: Still creating... [10s elapsed]
aws_autoscaling_group.kubedeploy: Still creating... [20s elapsed]
aws_autoscaling_group.kubedeploy: Still creating... [30s elapsed]
aws_autoscaling_group.kubedeploy: Still creating... [40s elapsed]
aws_autoscaling_group.kubedeploy: Creation complete after 47s [id=terraform-eks-demo15]
null_resource.configure-kubectl-local: Creating...
null_resource.configure-kubectl-local: Provisioning with 'local-exec'...
null_resource.configure-kubectl-local (local-exec): Executing: ["/bin/sh" "-c" "      aws eks update-kubeconfig --name terraform-eks-demo15 --region us-east-1 --kubeconfig ~/.kube/config;\n      kubectl config use-context arn:aws:eks:us-east-1:999323281678:cluster/terraform-eks-demo15;\n"]
null_resource.configure-kubectl-local (local-exec): Updated context arn:aws:eks:us-east-1:999323281678:cluster/terraform-eks-demo15 in /Users/ryan/.kube/config
null_resource.configure-kubectl-local (local-exec): Switched to context "arn:aws:eks:us-east-1:999323281678:cluster/terraform-eks-demo15".
null_resource.configure-kubectl-local: Creation complete after 5s [id=2955329731185507847]
null_resource.apply-auth-config-map: Creating...
null_resource.apply-auth-config-map: Provisioning with 'local-exec'...
null_resource.apply-auth-config-map (local-exec): Executing: ["/bin/sh" "-c" "cat <<EOF | kubectl apply -f -\n\n\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: aws-auth\n  namespace: kube-system\ndata:\n  mapRoles: |\n    - rolearn: arn:aws:iam::999323281678:role/terraform-eks-demo15-node\n      username: system:node:{{EC2PrivateDNSName}}\n      groups:\n        - system:bootstrappers\n        - system:nodes\n\nEOF"]
null_resource.apply-auth-config-map (local-exec): configmap/aws-auth created
null_resource.apply-auth-config-map: Creation complete after 9s [id=8879267702225573169]
kubernetes_service_account.tiller: Creating...

Error: Post https://F5B5BA857F9BC6E03481CE526B29D3B2.sk1.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/serviceaccounts: dial tcp: lookup F5B5BA857F9BC6E03481CE526B29D3B2.sk1.us-east-1.eks.amazonaws.com on 192.168.156.1:53: no such host

  on kubernetes.tf line 7, in resource "kubernetes_service_account" "tiller":
   7: resource "kubernetes_service_account" "tiller" {


➜  terraform-base2 git:(master) ✗ terraform apply
data.aws_region.current: Refreshing state...
data.aws_availability_zones.available: Refreshing state...
aws_vpc.kubedeploy: Refreshing state... [id=vpc-00e283ddc4e9cec6d]
aws_iam_role.kube-node: Refreshing state... [id=terraform-eks-demo15-node]
aws_iam_role.kube-cluster: Refreshing state... [id=terraform-eks-demo15]
aws_iam_role_policy_attachment.kube-node-AmazonEC2ContainerRegistryReadOnly: Refreshing state... [id=terraform-eks-demo15-node-20190607134547401900000001]
aws_iam_instance_profile.kube-node: Refreshing state... [id=terraform-eks-demo15]
aws_iam_role_policy_attachment.kube-node-AmazonEKS_CNI_Policy: Refreshing state... [id=terraform-eks-demo15-node-20190607134547536300000005]
aws_iam_role_policy_attachment.kube-node-AmazonEKSWorkerNodePolicy: Refreshing state... [id=terraform-eks-demo15-node-20190607134547528000000003]
aws_iam_role_policy_attachment.cluster-AmazonEKSClusterPolicy: Refreshing state... [id=terraform-eks-demo15-20190607134547528100000004]
aws_iam_role_policy_attachment.cluster-AmazonEKSServicePolicy: Refreshing state... [id=terraform-eks-demo15-20190607134547401900000002]
aws_security_group.kube-cluster: Refreshing state... [id=sg-03a4e22ab6c9b4923]
aws_subnet.kubedeploy[1]: Refreshing state... [id=subnet-09699e43fb6abb60e]
aws_subnet.kubedeploy[0]: Refreshing state... [id=subnet-013b2d3b2e63a3334]
aws_security_group.kube-node: Refreshing state... [id=sg-0335024ca07abe7c6]
aws_internet_gateway.kubedeploy: Refreshing state... [id=igw-07b00fd1d8813db0e]
aws_security_group_rule.kube-node-ingress-self: Refreshing state... [id=sgrule-1908758964]
aws_route_table.kubedeploy: Refreshing state... [id=rtb-0a60a575bc6951c30]
aws_security_group_rule.cluster-ingress-workstation-https: Refreshing state... [id=sgrule-741747196]
aws_security_group_rule.kube-node-ingress-cluster: Refreshing state... [id=sgrule-2036271370]
aws_security_group_rule.cluster-ingress-node-https: Refreshing state... [id=sgrule-118053593]
aws_eks_cluster.kube-cluster: Refreshing state... [id=terraform-eks-demo15]
aws_route_table_association.kubedeploy[0]: Refreshing state... [id=rtbassoc-0a629c6dd96ec4a8a]
aws_route_table_association.kubedeploy[1]: Refreshing state... [id=rtbassoc-011badb3b87b6564a]
data.aws_ami.eks-worker: Refreshing state...
aws_launch_configuration.kubedeploy: Refreshing state... [id=terraform-eks-demo1520190607135533997000000006]
aws_autoscaling_group.kubedeploy: Refreshing state... [id=terraform-eks-demo15]
null_resource.configure-kubectl-local: Refreshing state... [id=2955329731185507847]
null_resource.apply-auth-config-map: Refreshing state... [id=8879267702225573169]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubernetes_cluster_role_binding.tiller will be created
  + resource "kubernetes_cluster_role_binding" "tiller" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "tiller"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }

      + role_ref {
          + api_group = "rbac.authorization.k8s.io"
          + kind      = "ClusterRole"
          + name      = "cluster-admin"
        }

      + subject {
          + api_group = (known after apply)
          + kind      = "ServiceAccount"
          + name      = "tiller"
          + namespace = "kube-system"
        }
    }

  # kubernetes_service_account.tiller will be created
  + resource "kubernetes_service_account" "tiller" {
      + automount_service_account_token = true
      + default_secret_name             = (known after apply)
      + id                              = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "tiller"
          + namespace        = "kube-system"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kubernetes_service_account.tiller: Creating...
kubernetes_service_account.tiller: Creation complete after 2s [id=kube-system/tiller]
kubernetes_cluster_role_binding.tiller: Creating...
kubernetes_cluster_role_binding.tiller: Creation complete after 1s [id=tiller]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

I can't figure out dependencies or kubeconfig sourcing.

**Comment by Carles-Figuerola** [comment]
We are finding the same behaviour, we have 3 resources (to simplify it), with `depends_on` between them. One creates the cluster:

```
module.eks_cluster_and_workers.null_resource.create_kubeconfig: Creating...
( . . . )
module.eks_cluster_and_workers.null_resource.create_kubeconfig (local-exec): Added new context default-compute to /home/jenkins/.kube/config
module.eks_cluster_and_workers.null_resource.create_kubeconfig: Creation complete after 0s [id=3452760103064663403]
```

The second one sets tiller and helm by running some kubectl bash commands

```
module.eks_cluster_and_workers.kubernetes_cluster_role_binding.read_only_users_cluster_role_binding: Creating...
( . . . )
module.eks_cluster_and_workers.null_resource.initialize_helm (local-exec): Executing: ["/bin/sh" "-c" "kubectl --context default-compute create serviceaccount --namespace kube-system tiller && kubectl --context default-compute create clusterrolebinding tiller-cluster-role --clusterrole=cluster-admin --serviceaccount=kube-system:tiller && helm --kube-context default-compute init --service-account tiller --upgrade --history-max 5"]
( . . . )
module.eks_cluster_and_workers.null_resource.initialize_helm (local-exec): serviceaccount/tiller created
module.eks_cluster_and_workers.null_resource.initialize_helm (local-exec): clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-role created
( . . . )
module.eks_cluster_and_workers.null_resource.initialize_helm: Creation complete after 12s [id=2331592505314248119]
```

And then we are leveraging the kubernetes provisioner to create some more roles, which fail in the same form as above, as if there were no kubeconfig (which is false and proven by the resource above)

```

Error: Post http://localhost/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: dial tcp 127.0.0.1:80: connect: connection refused

  on .terraform/modules/eks_cluster_and_workers/terraform/modules/eks-cluster-and-workers/readonly_user_role.tf line 37, in resource "kubernetes_cluster_role_binding" "read_only_users_cluster_role_binding":
  37: resource "kubernetes_cluster_role_binding" "read_only_users_cluster_role_binding" {

```

**Comment by paultyng** [comment]
This seems like the upstream progressive apply issue: https://github.com/hashicorp/terraform/issues/4149

You cannot currently (reliably) chain together a provider's config with the output of a resource (in this case making the provider depend on the output of the `null_resource`).

**Comment by nishubharti** [comment]
> Hi there,
> 
> Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
> 
> ### Terraform Version
> 1.7
> 
> ### Affected Resource(s)
> Please list the resources as a list, for example:
> 
> * kubernetes_service_account
> 
> ### Terraform Configuration Files
> ```terraform
> resource "null_resource" "configure-kubectl-local" {
> 
>   provisioner "local-exec" {
>     command = <<EOT
>       aws eks update-kubeconfig --name ${var.cluster_name} --region ${var.aws_region} --kubeconfig .kube-config.yaml;
>    EOT
>   }
>   depends_on = [
>     "aws_eks_cluster.kube-cluster",
>     "aws_autoscaling_group.kubedeploy"
>   ]
> }
> 
> provider "kubernetes" {
>   version = "~> 1.7"
>   config_path = "./.kube-config.yaml"
> }
> 
> resource "kubernetes_service_account" "tiller" {
>   metadata {
>     name      = "tiller"
>     namespace = "kube-system"
>   }
> 
>   automount_service_account_token = true
> 
>   depends_on = [
>     "aws_eks_cluster.kube-cluster",
>     "null_resource.apply-auth-config-map",
>     "null_resource.configure-kubectl-local"
>   ]
> }
> 
> resource "kubernetes_cluster_role_binding" "tiller" {
>   metadata {
>     name = "tiller"
>   }
> 
>   role_ref {
>     kind      = "ClusterRole"
>     name      = "cluster-admin"
>     api_group = "rbac.authorization.k8s.io"
>   }
> 
>   subject {
>     kind = "ServiceAccount"
>     name = "tiller"
> 
>     api_group = ""
>     namespace = "kube-system"
>   }
> 
>   depends_on = ["kubernetes_service_account.tiller"]
> }
> ```
> 
> ### Debug Output
> https://gist.github.com/nitrag/59991d5520f55f61a46e212c8af507ac
> 
> ### Expected Behavior
> I'm expecting the kubernetes provider to pickup the KUBECONFIG (`kubernetes.config_path`) that is generated after my k8s cluster is created. My goal is to run `terraform apply` and have it spin up cluster, provision kubernetes, and install helm charts all in one run.
> 
> ### Actual Behavior
> It's not honoring/finding the local KUBECONFIG file and trying to connect to a localhost kubernetes cluster. **I imagine the kubernetes provider is trying to load the file from `config_path` at the start of `terraform apply` instead of on-the-fly** because it fails the first time and I run `terraform apply` a second time and it works instantly the second time.
> 
> ### Steps to Reproduce
> Please list the steps required to reproduce the issue, for example:
> 
> 1. `terraform apply`
> 2. Get `Error: Post http://localhost/api/v1/namespaces/kube-system/serviceaccounts: dial tcp 127.0.0.1:80: connect: connection refused`
> 3. `terraform apply`
> 
> ### Important Factoids
> AWS EKS
> 
> ### References



> Hi there,
> 
> Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
> 
> ### Terraform Version
> 1.7
> 
> ### Affected Resource(s)
> Please list the resources as a list, for example:
> 
> * kubernetes_service_account
> 
> ### Terraform Configuration Files
> ```terraform
> resource "null_resource" "configure-kubectl-local" {
> 
>   provisioner "local-exec" {
>     command = <<EOT
>       aws eks update-kubeconfig --name ${var.cluster_name} --region ${var.aws_region} --kubeconfig .kube-config.yaml;
>    EOT
>   }
>   depends_on = [
>     "aws_eks_cluster.kube-cluster",
>     "aws_autoscaling_group.kubedeploy"
>   ]
> }
> 
> provider "kubernetes" {
>   version = "~> 1.7"
>   config_path = "./.kube-config.yaml"
> }
> 
> resource "kubernetes_service_account" "tiller" {
>   metadata {
>     name      = "tiller"
>     namespace = "kube-system"
>   }
> 
>   automount_service_account_token = true
> 
>   depends_on = [
>     "aws_eks_cluster.kube-cluster",
>     "null_resource.apply-auth-config-map",
>     "null_resource.configure-kubectl-local"
>   ]
> }
> 
> resource "kubernetes_cluster_role_binding" "tiller" {
>   metadata {
>     name = "tiller"
>   }
> 
>   role_ref {
>     kind      = "ClusterRole"
>     name      = "cluster-admin"
>     api_group = "rbac.authorization.k8s.io"
>   }
> 
>   subject {
>     kind = "ServiceAccount"
>     name = "tiller"
> 
>     api_group = ""
>     namespace = "kube-system"
>   }
> 
>   depends_on = ["kubernetes_service_account.tiller"]
> }
> ```
> 
> ### Debug Output
> https://gist.github.com/nitrag/59991d5520f55f61a46e212c8af507ac
> 
> ### Expected Behavior
> I'm expecting the kubernetes provider to pickup the KUBECONFIG (`kubernetes.config_path`) that is generated after my k8s cluster is created. My goal is to run `terraform apply` and have it spin up cluster, provision kubernetes, and install helm charts all in one run.
> 
> ### Actual Behavior
> It's not honoring/finding the local KUBECONFIG file and trying to connect to a localhost kubernetes cluster. **I imagine the kubernetes provider is trying to load the file from `config_path` at the start of `terraform apply` instead of on-the-fly** because it fails the first time and I run `terraform apply` a second time and it works instantly the second time.
> 
> ### Steps to Reproduce
> Please list the steps required to reproduce the issue, for example:
> 
> 1. `terraform apply`
> 2. Get `Error: Post http://localhost/api/v1/namespaces/kube-system/serviceaccounts: dial tcp 127.0.0.1:80: connect: connection refused`
> 3. `terraform apply`
> 
> ### Important Factoids
> AWS EKS
> 
> ### References

@nitrag did you got its solution?I am also facing the same problem.

**Comment by nishubharti** [comment]
@nitrag did you got the solution.I am also facing the same issue.

**Comment by nitrag** [comment]
No solution. It's annoying, just run `terraform apply` twice.

**Comment by nishubharti** [comment]
Mine is not even working with running terraform apply twice.

**Comment by nitrag** [comment]
Try outputting a kube-config local to terraform. 

```
resource "null_resource" "configure-kubectl-local" {
  provisioner "local-exec" {
    command = <<EOT
    aws eks update-kubeconfig --name ${var.cluster_name} --region ${var.aws_region} --kubeconfig ./kube-config.yaml;
EOT
  }

  depends_on = [
    "aws_eks_cluster.kube-cluster",
    "aws_autoscaling_group.default",
  ]
}
```

You will need to set this before running terraform apply.
```
export KUBECONFIG=$(pwd)/kube-config.yaml;
```

**Comment by vrathore18** [comment]
This issue is not resolved. please don't close this issue. we are still facing this error.

**Comment by chargraves85** [comment]
bump

**Comment by nitrag** [comment]
I guess the real workaround is to pass the values in directly, utilizing `depends_on`.

```
provider "kubernetes" {
  version = "~> 1.10"

  load_config_file       = false
  host                   = var.k8s_endpoint
  cluster_ca_certificate = var.k8s_ca_certificate
  token                  = var.k8s_token
}
provider "helm" {
  version = "~> 0.9"
  kubernetes {
    host                   = var.k8s_endpoint
    cluster_ca_certificate = var.k8s_ca_certificate
    token                  = var.k8s_token
    load_config_file       = false
  }

  debug           = true
  install_tiller  = true
  service_account = kubernetes_service_account.tiller.metadata.0.name
  namespace       = kubernetes_service_account.tiller.metadata.0.namespace
}
```
