### ISSUE TITLE
Support `priorityClassName` for pods (deployments, daemonset, etc)

### ISSUE THREAD

**Issue by wjam** [terraform-providers/terraform-provider-kubernetes#506]
1.14 made the pod priority feature stable, so the provider should be updated to expose this functionality.

This will require updating the Kubernetes API library to 1.14 from 1.11.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core

**Comment by tdmalone** [comment]
Somewhat related: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/495

**Comment by dayglojesus** [comment]
Looking forward to seeing this implemented as it is now a stable feature and EKS 1.14 is available. Without this feature, scheduling critical pods or daemonsets for autoscaling nodes, requires some fragile workarounds.
