### ISSUE TITLE
Feature request: support digitalocean in kubernetes_persistent_volime

### ISSUE THREAD

**Issue by mkjmdski** [terraform-providers/terraform-provider-kubernetes#509]
Hey!
There are various providers already supporting creating volumes which could be used as persitent volume in k8s. One of them is digitalocean https://www.digitalocean.com/docs/kubernetes/how-to/add-volumes/ and it would be great to codify that via terraform. I think this somehow correlates with #296

**Comment by aareet** [comment]
I believe this is better tracked in #296 - please reopen if you disagree.
