### ISSUE TITLE
Feature Request: Ingress data source

### ISSUE THREAD

**Issue by andyyaldoo** [terraform-providers/terraform-provider-kubernetes#514]
Hi there,

I just would like to ask if it is possible and worth to add `data_source_kubernetes_ingress`. I just have a simple use case to get the `load_balancer_ingress.hostname` and create a dns record with cloudflare provider. and I don't mind to give it a go myself :)

Thanks in advance.

**Comment by thommaa** [comment]
I will add the documentation for the data source kubernetes_ingress

**Comment by thommaa** [comment]
#612 This PR has the implementation of the datasource kubernetes_ingress
We have the use case to get the AWS ALB ingress (created from a helm chart ingress annotation) and use it in terraform.

**Comment by thommaa** [comment]
PR #615 is waiting for review, approval and merge. @aareet @dak1n1

**Comment by dak1n1** [comment]
This feature has been merged and will be available in the next release.
