### ISSUE TITLE
Feature Request: Allow for reading raw kubeconfig.

### ISSUE THREAD

**Issue by brunomiguelcustodioform3** [terraform-providers/terraform-provider-kubernetes#529]
In Terraform Enterprise, every `plan`/`apply` phase runs on its own Docker container, which gets discarded afterwards. This kind of makes `config_path` unusable in these scenarios unless the kubeconfig file itself is checked-in to source control (otherwise it is not present during, say, the `plan` phase).

I'd like to propose that the provided starts accepting a `raw_config` or `config_value` argument which takes the full (raw) kubeconfig and uses that to configure itself. If this sounds like a reasonable feature, I'd be available and willing to work on that.

**Comment by alexsomesan** [comment]
I'm going to delete this issue so Bruno can re-open it with his other GitHub account, instead of the corporate one.
