### ISSUE TITLE
generic kubectl resource for yaml manifests

### ISSUE THREAD

**Issue by marcosrmendezthd** [terraform-providers/terraform-provider-kubernetes#556]
Would it be possible to create a resource to create/apply manifests and destroy them in order to support features that can't be mapped directly on terraform, such as the custom stackdriver metrics adapter?

The contents could be a file or inlined.

kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-stackdriver/master/custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml

I've been trying to workaround this by using null_resources and running kubectl commands, but sometimes this [issue](https://github.com/hashicorp/terraform/issues/13549) bites me.

### Terraform Version
Terraform v0.11.14

**Comment by hassenius** [comment]
+1

Particularly now that custom resource definitions are becoming more and more common, it will be impossible to map all this into terraform directly, so having a "create" and "delete" on a arbitrary yaml file without having to configure kubectl separately from the kubernetes provider would be very useful

**Comment by BrandonStiff** [comment]
Agreed, and for the same reason.

**Comment by marcosrmendezthd** [comment]
maybe adopt https://github.com/Typeform/terraform-provider-kubectl ?

**Comment by guhcampos** [comment]
Just to mention a few use cases even more common than stackdriver:

Install nginx-ingress as per: https://kubernetes.github.io/ingress-nginx/deploy/
Install cert-manager as per: https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html
Install argocd as per: https://github.com/argoproj/argo-cd/blob/master/docs/getting_started.md

All these require a simple `kubectl apply -f` to a URL like the original example and cannot be implemented in Terraform right now.

**Comment by oxplot** [comment]
Another workaround is to use helm provider and create a chart. It works quite robustly and doesn't depend on external binaries.

**Comment by marshallford** [comment]
I'm running into the same issue.

**Comment by dak1n1** [comment]
CRD support is being tracked in #215
