### ISSUE TITLE
PVC storage_class_name empty sets default storage class

### ISSUE THREAD

**Issue by davidq2q** [terraform-providers/terraform-provider-kubernetes#567]
Hello,

There is a critical bug for the kubernetes terraform provider that has been reported since 2017 but is still open.

See:
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/102
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/339

What happens is that terraform is not passing the empty storage class string instead somehow the pvc's are created with the default storage class. The work around mentioned by using label selectors is not working anymore on terraform 0.12.

Best regards,
David

**Comment by ajchiarello** [comment]
I was able to work around this by creating a dummy storage class that I applied to the PV and the PVC - not ideal, but it did work.

**Comment by davidq2q** [comment]
@ajchiarello how did you set up the dummy class?

**Comment by lawliet89** [comment]
I opened #590 to fix this.

**Comment by koxu1996** [comment]
Any updates on merging this? Bug is really annoying.

**Comment by leonbreedt** [comment]
+1, this is a blocker for using PVCs in our scenario, and we have to do volume mounts directly on the pod template spec, which does not allow us to override mount options, which breaks our scenario.

**Comment by dak1n1** [comment]
Hi, we have a few issues relating to this that are being consolidated here: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/872 See the new issue for a work-around. Thanks!
