### ISSUE TITLE
Deployments made under extensions/v1beta1 API version instead of apps/v1

### ISSUE THREAD

**Issue by enozero** [terraform-providers/terraform-provider-kubernetes#573]
### Terraform Version
```
Terraform v0.12.1
+ provider.kubernetes v1.8.1
```

### Kubernetes Cluster Version
`Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

### Affected Resource(s)
- `kubernetes_deployment`

### Terraform Configuration Files
https://gist.github.com/enozero/4fbc9d18b7bcba4070532e136b37c323

### Debug Output
https://gist.github.com/enozero/4fbc9d18b7bcba4070532e136b37c323

### Expected Behavior
The API version is `apps/v1`.

### Actual Behavior
The API version is `extensions/v1beta1`. Kubernetes 1.16 will remove `extensions/v1beta1`, `extensions/v1beta2`, `apps/v1beta1`, and `apps/v1beta2` APIs, scheduled to be released this in October 2019.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
When viewing the trace, it looks like it is calling the right Kubernetes API:

>`2019-07-29T21:59:53.115Z [DEBUG] plugin.terraform-provider-kubernetes_v1.8.1_x4: 2019/07/29 21:59:53 [INFO] Creating new deployment: v1.Deployment{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.DeploymentSpec{Replicas:(*int32)(0xc00053751c), Selector:(*v1.LabelSelector)(0xc00062df00), Template:v1.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"test"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.PodSpec{Volumes:[]v1.Volume(nil), InitContainers:[]v1.Container(nil), Containers:[]v1.Container{v1.Container{Name:"test", Image:"alpine:3.10.1", Command:[]string{}, Args:[]string{}, WorkingDir:"", Ports:[]v1.ContainerPort(nil), EnvFrom:[]v1.EnvFromSource(nil), Env:[]v1.EnvVar(nil), Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), Requests:v1.ResourceList(nil)}, VolumeMounts:[]v1.VolumeMount(nil), VolumeDevices:[]v1.VolumeDevice(nil), LivenessProbe:(*v1.Probe)(nil), ReadinessProbe:(*v1.Probe)(nil), Lifecycle:(*v1.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"", ImagePullPolicy:"", SecurityContext:(*v1.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc000537528), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string{}, ServiceAccountName:"", DeprecatedServiceAccount:"", AutomountServiceAccountToken:(*bool)(0xc000537524), NodeName:"", HostNetwork:false, HostPID:false, HostIPC:false, ShareProcessNamespace:(*bool)(0xc000537525), SecurityContext:(*v1.PodSecurityContext)(nil), ImagePullSecrets:[]v1.LocalObjectReference{}, Hostname:"", Subdomain:"", Affinity:(*v1.Affinity)(nil), SchedulerName:"", Tolerations:[]v1.Toleration(nil), HostAliases:[]v1.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*v1.PodDNSConfig)(nil), ReadinessGates:[]v1.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}, Strategy:v1.DeploymentStrategy{Type:"", RollingUpdate:(*v1.RollingUpdateDeployment)(nil)}, MinReadySeconds:0, RevisionHistoryLimit:(*int32)(0xc000537520), Paused:false, ProgressDeadlineSeconds:(*int32)(0xc000537518)}, Status:v1.DeploymentStatus{ObservedGeneration:0, Replicas:0, UpdatedReplicas:0, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:0, Conditions:[]v1.DeploymentCondition(nil), CollisionCount:(*int32)(nil)}}`

One thing about that log that sticks out is this:
`TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}`

Looks like the API (perhaps on the server side) is defaulting to the lowest possible API. That contradicts the [API documentation](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#TypeMeta):
> APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values.

Does that `APIVersion` need to be set?

**Comment by josmo** [comment]
I believe this is actually tied to api groups and defaults vs using the "latest". where the api server can set which groups are at which version. In this case since tf is using the golang client, the server is saying that the api group for deployments should use extensions vs v1.  I'm not 100% sure about this but if someone that knows want's to confirm, I believe the provider will match what the golang client/k8s server is enforcing.

**Comment by enozero** [comment]
Is the server saying that the client should use it or can use it? The client, if called upon by a specific version, in this provider's case is the `apps/v1` API, should use that version. The server shouldn't be downforcing an API call. That seems like a major bug in the golang client code. It seems like certain versions can be [turned off](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#enabling-resources-in-the-groups).

**Comment by maps90** [comment]
any update on this? there's a breaking changes on 1.16, ``` extensions/v1beta1``` are removed.

**Comment by pdecat** [comment]
Deployments have been created using the Apps v1 API since the beginning: https://github.com/terraform-providers/terraform-provider-kubernetes/blame/v1.10.0/kubernetes/resource_kubernetes_deployment.go#L212

Acceptance tests against kubernetes 1.16 do pass successfully.

@maps90 did you face an error or are you just assuming it will break?

**Comment by komljen** [comment]
This is not related to TF, even if I install some community helm chart I get the same result, for example:

```
$ helm install test stable/grafana
$ kubectl get deploy test-grafana -o json | jq .apiVersion
"extensions/v1beta1"
```

When running `helm install` with debug mode, I see that deployment template is rendered with `apps/v1`:

```
$ helm install test stable/grafana --dry-run --debug | grep -A 1 grafana/templates/deployment.yaml
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
```

Checking both APIs version priority reveals that `extensions/v1beta1` is preferred, or maybe I read this wrong:
```
$ kubectl get apiservices.apiregistration.k8s.io v1.apps -o json | jq .spec.versionPriority
15

$ kubectl get apiservices.apiregistration.k8s.io v1beta1.extensions -o json | jq .spec.versionPriority
1
```

**Comment by mailjunze** [comment]
Deep diving into this I found objects  created in K8s stored in the latest stable API group. In case of deployment that is apps/v1. When you create a deployment using "extensions/v1beta1" in k8s 1.15, it will be stored in ETCD within the "apps/v1" API group, however, when retrieving you can request for  any supported API group for that k8s version.
## 1.15
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.apps nginx-deployment -o json  | jq .apiVersion
"apps/v1"
```
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.extension nginx-deployment -o json  | jq .apiVersion
"extensions/v1beta1"
```
##  1.16
```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.apps nginx-deployment -o json  | jq .apiVersion
"apps/v1"
```

```
ec2-user@ip-172-31-9-12:~
▶ kubectl get deployment.extension nginx-deployment -o json  | jq .apiVersion
error: the server doesn't have a resource type "deployment"
```
Without mentioning the API group, In k8s 1.15 for backwards compatibility, client retrieves extensions API group first. 
```
kubectl get deployment nginx-deployment -o json  | jq .apiVersion
"extensions/v1beta1"
```
There is no extension API group supported for deployment in 1.16, so client retrieves  only apps/v1
```
kubectl get deployment nginx-10range -o json  | jq .apiVersion
"apps/v1"
```

[sig-architecture/api_changes.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md)
https://github.com/kubernetes/kubernetes/issues/58131#issuecomment-356823588

To make sure all objects are stored in current stable API version, A simple get/put is enough after cluster upgrade is enough.

"kubectl get deployment --all-namespaces -o json | kubectl replace -f - "

Objects that don't need migration will no-op (Already have the latest stable APIVersion in etcd). Objects that do need migration will persist in the new preferred/stable API version.
