### ISSUE TITLE
Publish GitHub releases during provider releases

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-kubernetes#608]
Releases are published by updating the changelog, pushing a binary, and making a GitHub "tag" release.
Users can't subscribe to these releases automatically, though: https://github.community/t5/How-to-use-Git-and-GitHub/Not-getting-release-notification-despite-quot-Watching-releases/td-p/19665.

It would be awesome to publish rich releases on GitHub, allowing users to subscribe.

Both the [Azure](https://github.com/terraform-providers/terraform-provider-azurerm/releases) and [AWS](https://github.com/terraform-providers/terraform-provider-aws/releases) providers do this already.

**Comment by guhcampos** [comment]
It would also be nice if such releases actually included the changelog data. Most terraform providers, this one included, have no mention of the changes since the last version in the Github Release.

**Comment by alexsomesan** [comment]
@guhcampos You can review the changes included in each provider release in the [CHANGELOG.md](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/CHANGELOG.md) file. We will look into including the relevant changes in the github release.

**Comment by guhcampos** [comment]
Thanks @alexsomesan! I'm aware of the content in the changelog, that's where I usually look. What I mean to suggest is that if the changelog content is added to the release, it will be included on the notifications @pdecat mentions so they'd be broadcast along with the release itself. Makes it a little bit easier to follow the progress as the user does not need to browse all the way to github.

**Comment by pdecat** [comment]
Current work-around: subscribe to https://github.com/terraform-providers/terraform-provider-kubernetes/tags.atom with an feed reader

**Comment by pdecat** [comment]
Github releases are now published during the release process since v1.10.0 :tada:

https://github.com/terraform-providers/terraform-provider-kubernetes/releases
