### ISSUE TITLE
Support Pod Distribution Budget

### ISSUE THREAD

**Issue by AndrewDryga** [terraform-providers/terraform-provider-kubernetes#644]
Hey guys. Are there are any plans to support PDBs and Vertical Pod Autoscalers? Currently, provider API is missing quite a few critical features and we would really like to stop using Helm for our apps.

**Comment by blt-gw** [comment]
The PDB request seems related to https://github.com/terraform-providers/terraform-provider-kubernetes/pull/338.

**Comment by AndrewDryga** [comment]
Closing as a duplicate for PR which is not merged for months 🙃.
