### ISSUE TITLE
kubernetes_api_service.spec.service.port  not supported

### ISSUE THREAD

**Issue by therc** [terraform-providers/terraform-provider-kubernetes#660]
### Terraform Version
Terraform v0.12.9
+ provider.aws v2.30.0
+ provider.kubernetes v1.9.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)
- kubernetes_api_service.spec.service

### Expected Behavior
Service references support the optional port, per
https://godoc.org/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1#ServiceReference

### Actual Behavior
There is no `port` argument.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/487

**Comment by pdecat** [comment]
Working on a PR.

**Comment by alexsomesan** [comment]
I'll work on testing and merging #638

**Comment by alexsomesan** [comment]
#663 also needs to merge first, otherwise the build is broken (by the upgrade to client-go v12).
Waiting on a review for that.

**Comment by therc** [comment]
Ah, that makes sense. I had missed that `port` was missing from the initial implementation. Thanks a lot!
