### ISSUE TITLE
kubernetes_priority_class import incorrectly requires a namespace

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-kubernetes#680]
### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.35.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- [kubernetes_priority_class](https://www.terraform.io/docs/providers/kubernetes/r/priority_class.html)

### Terraform Configuration Files
```hcl
resource "kubernetes_priority_class" "monitoring_critical" {
  metadata {
    name = "monitoring-critical"
  }

  value       = 1900000
  description = "Used for pods that are critical for monitoring workloads."
}
```

### Expected Behavior
The existing `PriorityClass` should be imported.

### Actual Behavior
The provider errored on import, requesting a namespace to be included:

```
$ terraform import kubernetes_priority_class.monitoring_critical monitoring-critical

kubernetes_priority_class.monitoring_critical: Importing from ID "monitoring-critical"...
kubernetes_priority_class.monitoring_critical: Import complete!
  Imported kubernetes_priority_class (ID: monitoring-critical)
kubernetes_priority_class.monitoring_critical: Refreshing state... (ID: monitoring-critical)

Error: kubernetes_priority_class.monitoring_critical (import id: monitoring-critical): 1 error occurred:
        * import kubernetes_priority_class.monitoring_critical result: monitoring-critical: kubernetes_priority_class.monitoring_critical: Unexpected ID format ("monitoring-critical"), expected "namespace/name".

Releasing state lock. This may take a few moments...
```

### Steps to Reproduce
1. Create a PriorityClass outside of Terraform
1. Set up the configuration as above
1. Run `terraform import kubernetes_priority_class.monitoring_critical monitoring-critical`
1. Observe error

### Important Factoids
- a PriorityClass is a non-namespaced object
- Using the name only and not the namespace matches the documentation at https://www.terraform.io/docs/providers/kubernetes/r/priority_class.html#import
- I tried importing with `default/monitoring-critical` just in case, but as expected, the resource could not be found ('Terraform detected a resource with this ID doesn't exist. Please verify the ID is correct. You cannot import non-existent resources using Terraform import.')
- Might relate to https://github.com/terraform-providers/terraform-provider-kubernetes/issues/681
- `kubernetes_priority_class` was just recently released in [v1.10.0](https://github.com/terraform-providers/terraform-provider-kubernetes/releases/tag/v1.10.0)

**Comment by lawliet89** [comment]
Try running it with `default/<name>`. It's a bit strange but probably something missed out during the implementation.

**Comment by tdmalone** [comment]
I tried that too - mentioned above under the Important Factoids - which resulted in an error saying the resource didn't exist (which makes sense).

**Comment by alexsomesan** [comment]
I've opened a PR to address this.
