### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by georgyvlad** [terraform-providers/terraform-provider-kubernetes#684]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
$ terraform -v
Terraform v0.12.13

Error when trying to install:
$ make build
==> Checking that code complies with gofmt requirements...
go install
go: github.com/keybase/go-crypto@v0.0.0-20190523171820-b785b22cc757: invalid pseudo-version: does not match version-control timestamp (2019-04-16T18:20:11Z)
make: *** [build] Error 1

**Comment by georgyvlad** [comment]
For now, I am past this problem when I do this change in "go.mod"
`
	//	github.com/keybase/go-crypto v0.0.0-20190523171820-b785b22cc757 // indirect
	github.com/keybase/go-crypto v0.0.0-20190416182011-b785b22cc757 // indirect
`

Now, I hit another issue:
`
build github.com/terraform-providers/terraform-provider-kubernetes: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.9.0+incompatible (/go/pkg/mod/github.com/!azure/go-autorest@v11.9.0+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.0 (/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0)
make: *** [build] Error 1
`

**Comment by pdecat** [comment]
Hi @georgyvlad, append this to `go.mod` to work it around:

```
replace github.com/keybase/go-crypto => github.com/keybase/go-crypto v0.0.0-20190416182011-b785b22cc757
replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.0+incompatible
go 1.13
```

**Comment by georgyvlad** [comment]
Thank you, @pdecat ! That worked.
