### ISSUE TITLE
Support VerticalPodAutoscaler resource

### ISSUE THREAD

**Issue by eddy-curv** [terraform-providers/terraform-provider-kubernetes#718]
### Terraform Version
Terraform v0.12.2
+ provider.google v3.3.0
+ provider.google-beta v3.3.0
+ provider.kubernetes v1.9.0

### Expected Behavior
Add support for vertical_pod_autoscaler resource

### Actual Behavior
While terraform-provider-google already added the option to turn on [VPA option in google_container_cluster resource](https://github.com/terraform-providers/terraform-provider-google/pull/5033), terraform-provider-kubernetes still lacks support of VPA resources.
Currently our workaround to create VPA's is based on a module with .yaml templates and null_resource with local-exec.

### References

- [VerticalPodAutoscaler](https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling)

**Comment by jrhouston** [comment]
@eddy-curv This resource actually isn't part of the [Kubernetes API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/), it is actually a CRD that is created by [this project](https://github.com/kubernetes/autoscaler). For the moment the provider doesn't support custom resources, but support is coming soon. See https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215.
