### ISSUE TITLE
How to find Jenkins password on Kubernetes through Terraform

### ISSUE THREAD

**Issue by jay8127** [terraform-providers/terraform-provider-kubernetes#740]
### Terraform Version 0.12.13, 0.11.13
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment
- kubernetes_service

### Terraform Configuration Files
provider "kubernetes" {
  host = "${var.host_ip_address}"

  client_certificate     = "${base64decode(var.client_certificate)}"
  client_key             = "${base64decode(var.client_key)}"
  cluster_ca_certificate = "${base64decode(var.cluster_ca_certificate)}"
}

resource "kubernetes_deployment" "jenkins-master" {
  metadata {
    name = "jenkins-master"
    namespace = "default"
    labels = {
      app = "jenkins"
      apptype = "master"
    }
  }
  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "jenkins"
        apptype = "master"
      }
    }
    template {
      metadata {
        labels = {
          app = "jenkins"
          apptype = "master"
        }
      }
      spec {
        container {
          image = "jenkins/jenkins:lts"
          name  = "jenkins"
          resources {
            limits {
              cpu    = "250m"
              memory = "256Mi"
            }
            requests {
              cpu    = "100m"
              memory = "128Mi"
            }
          }
          port {
            container_port = 8080
            name = "http-port"
          }
          port {
            container_port = 50000
            name = "jnlp-port"
          }
          volume_mount {
            name = "jenkins-home"
            mount_path = "/var/jenkins_home"
          }
//          command = [
//              "cd /var/jenkins_home",
//              "ls",
//            "cat /var/jenkins_home/secrets/initialAdminPassword"]
        }
        volume {
          name = "jenkins-home"
        }
      }
    }
  }
}

/*resource "null_resource" "service_account" {

  provisioner "remote-exec" {
    connection {
      host = "${replace("${replace("${var.host_ip_address}", ":443", "")}", "https://", "")}"
      type = "ssh"
      user = "${var.admin_username}"
      private_key = "${file("${var.ssh_private_key}")}"
    }

    //inline = [
    //  "printf $(kubectl get secret --namespace default jenkins -o jsonpath={.data.jenkins-admin-password} | base64 --decode);echo"
    //]
    inline = [
      "ls -a"
    ]
  }
  depends_on = ["kubernetes_deployment.jenkins-master"]
}*/

resource "kubernetes_service" "jenkins-master" {
  metadata {
    name = "jenkins-master-service"
    namespace = "default"
  }
  spec {
    type = "LoadBalancer"
    selector = {
      app = "jenkins"
      apptype = "master"
    }
    port {
      port = 8080
      target_port = 8080
    }
  }
}
### Debug Output
SSH connection times out to the cluster

I am trying to find Jenkins initial admin password, I tried to achieve this with two options as below:
1) use a Null resource (please refer to commented code), connect to K8s cluster through ssh connection using remote-exec, and execute kubectl command to find out Jenkins admin password. But the SSH connection itself times out. I even tried to connect through SSH from my local machine but that too times out.
2) user "command" block in the container, and try to execute shell command in it. This says Error, but no description of any error and still looks like deployment is completed.

How can I achieve this use case to find Jenkins initial admin password on my K8s cluster using Terraform?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by alexsomesan** [comment]
Hello @jay8127,

From what I can tell you are looking for guidance on general usage of Terraform in conjunction with Kuberenetes. The issues sections in this repository is intended for reporting malfunctions / problems and missing features specific to the Kubernetes provider itself.

To best target the audience that can provide you with the answer you are looking for, I recommend you address this question in the community forums we have avaible. 
Please read about them here: https://www.terraform.io/community.html

There is also a Slack channel dedicated to Terraform providers in the Kubernetes Slack org.
You can find it here:https://kubernetes.slack.com/archives/CJY6ATQH4

I'll close this issue now since it doesn't address a problem specific to the Kubernetes provider.
