### ISSUE TITLE
load_config_file parameter not honored.

### ISSUE THREAD

**Issue by tgermain** [terraform-providers/terraform-provider-kubernetes#752]
### Terraform Version
```
Terraform v0.12.12
+ provider.kubernetes v1.10.0
```

### Affected Resource(s)
All kubernetes resources that needs at some point to connect to a kubernetes cluster. 

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  version          = "~> 1.5"
  load_config_file = false

  host                   = <my host for cluster A>
  token                  = <my token>
  cluster_ca_certificate = <my ca_cert>
}

resource "kubernetes_secret" "test-secret" {
    data = <REDACTED>
    type = "Opaque"

    metadata {
        name      = "a-secret"
        namespace = "a-namespace"
    }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
The local configuration should not be loaded.

### Actual Behavior
The local configuration is loaded.

#### Case 1:
if I run a `terraform plan` with an existing `~/.kube/config` file with the cluster A set as my current context, plan works.

#### Case 2:
If I change my context to cluster B through `~/.kube/config` (note: without changing the provider configuration nor my kubernetes resources), plan succeed but show me differences:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubernetes_secret.test-secret will be created
  + resource "kubernetes_secret" "test-secret" {
      + data = (sensitive value)
      + id   = (known after apply)
      + type = "Opaque"

      + metadata {
          + generation       = (known after apply)
          + labels           = {
              + "jenkins.io/credentials-type" = "secretFile"
            }
          + name             = "a-secret"
          + namespace        = "a-namespace"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

That secret already exist in cluster A but not in cluster B.

#### Case 3:
If I remove my local config file (`mv ~/.kube/config ~/.kube/config.bk` for instance), the `terraform plan` fails with:

```
Error: Get http://localhost/api/v1/namespaces/a-namespace/secrets/a-secret: dial tcp [::1]:80: connect: connection refused
```

It tries to reach the local kubernetes cluster which is the default for this provider.

----------

Note that if you reuse _case 1_ context (a local configuration file and current-context pointing to the right cluster) and run the plan with `KUBE_LOAD_CONFIG_FILE=false`, you end up with the same error as case 3.

### Important Factoids
My takes here are:
- Setting `load_config_file` parameter in configuration file to `false` is not honored as shown in my examples.
- Defaulting the environment variable to true if it is not defined [here](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L104) does not play well with the `load_config_file` being optional.

This default setting eases local development (you usually have kubernetes context on localhost, usually pointing to the kubernetes cluster your are working on) but hides issues: 

When you run the same terraform code on a different host, for instance in your CI, you will end up with the same error as in case 3. You do not necessarily have a kubeconfig on this other host and the provider will to contact a cluster on localhost because it is the default setting.

**Comment by alexsomesan** [comment]
Hi, I took the configuration sample you provided and tried to reproduce but I wasn't able to.
In all cases mentioned above the provider behaves as expected (uses the credentials provided in the provider block) and connects as expected.

In order to get to the bottom of this, I think we need to start looking at the environment where you are running Terraform. Would you be able to supply some more data, for example which OS are you running on, are you running Terraform in Docker or in a Kubernetes Pod?

The last error message you provided usually occurs when no credentials are supplied at all.

**Comment by tgermain** [comment]
Hi! 

This is a bit embarrassing: while trying to provide a better example (and not an extract of my production configuration with redacted or obfuscated bits), I could not reproduce my issue with a simple example.

I think we pinpoint it with a colleague: 

Our faulty resource was created in a module. 

In that module we defined empty provider that are meant as placeholder. The module caller pass providers to the module [explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly).

The module looks like : 
```hcl
provider "kubernetes" {
  alias = "jenkins"
}
resource "kubernetes_secret" "my_secret" {

  metadata {
    name      = "a-name"
    namespace = "a-namespace"
  }

  data = {
    REDACTED
  }

  type = "Opaque"
}

```

And that's how we call this module : 
```hcl
provider "kubernetes" {
# [skipped]
    load_config_file = false
}

provider "kubernetes {
    alias="jenkins"
    load_config_file = false
# [skipped]
}
module "monolith" {
  source                        = "git@github.com:REDACTED"
# [ skip variables passed to the module ]


  providers = {
    google             = google
    google.dns         = google.dns
# here we instruct the module to use the caller kubernetes.jenkins provider as its kubernetes.jenkins provider. 
# This module call works well and we have the expected behavior for load_config_file on the provider configuration
    kubernetes.jenkins = kubernetes.jenkins
  }
}
```

And I think on some of our project deployments we pass the providers the wrong way : 
```hcl
module "monolith" {
  source                        = "git@github.com:REDACTED"
# [ skip variables passed to the module ]
  providers = {
    google             = google
    google.dns         = google.dns
# this `kubernetes` provider on the left is never used in the module
# Meaning that the kubernetes.jenkins provider in the module get the default configuration and try to reach a local kubernetes cluster or, if a kube-context file is present, us the current local kube-context.
    kubernetes = kubernetes.jenkins
  }
}
```

And no other resources use the kubernetes.jenkins provider. We discover that terraform does not check the configuration of a provider that is not referenced by any resources. 

That explains why the behavior of the module did not change when we change the configuration of the kubernetes.jenkins provider as it was not referenced nor used.

If we fix how the providers are passed (using `kubernetes.jenkins = kubernetes.jenkins` stanza), we get the right and expected behavior. We also found that the kubernetes.jenkins provider was misconfigured.

It was not related at all to the kubernetes provider, sorry for the noise and thank you for your time!
