### ISSUE TITLE
Feature Request: ConfigMap data source

### ISSUE THREAD

**Issue by bonifaido** [terraform-providers/terraform-provider-kubernetes#76]
I think it would be beneficial to read ConfigMaps via Terraform, in my use case I would like to read the configmap that Calico provides: `calico-config` to be able to create new resources with Terraform based on the data in that ConfigMap.

**Comment by bluemalkin** [comment]
Any update on this ? Would love to see it released asap. Thanks !

**Comment by bmcstdio** [comment]
I am not sure why #90 was close, but I could probably work on this as I'd also benefit from it 🙂

**Comment by bonifaido** [comment]
Me neither :), it looks totally implemented (but closed).

**Comment by justinm** [comment]
I have a scenario where I need to be able to read configMaps into Terraform. +1 for this feature.

**Comment by jeremych1000** [comment]
Would it be possible to reopen the PR? We already have a `kubernetes_secret` data source, but no `kubernetes_config_map` data source.

**Comment by dak1n1** [comment]
Hi, everyone! This feature has merged and will appear in the next release. Please let us know if it's still an issue after upgrading your provider. Thanks!
