### ISSUE TITLE
No documents about : How to use kubernetes_secret ?

### ISSUE THREAD

**Issue by OrangePieiep** [terraform-providers/terraform-provider-kubernetes#760]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.12.20

How to translate these lines into HCL? I can't find examples in the documents...

kubectl create secret generic my-credentials --from-literal=admin-user=my_admin --from-literal=admin-password=123456

kubectl create secret tls grafana-ssl-certs --cert ./my.com.cert  --key ./my.com.key

**Comment by agadelshin** [comment]
Hi there!
please look at example on official provider doc page: https://www.terraform.io/docs/providers/kubernetes/r/secret.html

**Comment by OrangePieiep** [comment]
Thanks for your replying
I use this command to get the yaml config..
kubectl get secret <your secret name> -o yaml.
I think you may need to add this into the documents

**Comment by alexsomesan** [comment]
This terraform provider does not support YAML manifests. You will have to express you resources in HCL, as is usual with all Terraform resources. Please carefully read the provider documentation and examples.
