### ISSUE TITLE
Bug: Post http://localhost/api/v1/namespaces/xxx/secrets

### ISSUE THREAD

**Issue by hazcod** [terraform-providers/terraform-provider-kubernetes#779]
### Terraform Version
Terraform v0.12.21

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
https://github.com/ironPeakServices/infrastructure/blob/feat/argo/modules/helm/logging.tf#L83

### Debug Output
https://github.com/ironPeakServices/infrastructure/runs/479201943?check_suite_focus=true

### Panic Output
```
 2020/03/02 09:36:00 [TRACE] [walkApply] Exiting eval tree: module.kubernetes.provider.kubernetes (close)
2020/03/02 09:36:00 [TRACE] vertex "module.kubernetes.provider.kubernetes (close)": visit complete
2020/03/02 09:36:00 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/03/02 09:36:00 [TRACE] statemgr.Filesystem: have already backed up original state/terraform.tfstate to state/terraform.tfstate.backup on a previous write
2020/03/02 09:36:00 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 311
2020/03/02 09:36:00 [TRACE] statemgr.Filesystem: writing snapshot at state/terraform.tfstate

Error: Post http://localhost/api/v1/namespaces/logging/secrets: dial tcp 127.0.0.1:80: connect: connection refused

  on modules/helm/logging.tf line 83, in resource "kubernetes_secret" "cloudflared_cert_pem":
  83: resource "kubernetes_secret" "cloudflared_cert_pem" {



Error: Post http://localhost/api/v1/namespaces/logging/secrets: dial tcp 127.0.0.1:80: connect: connection refused

  on modules/helm/logging.tf line 106, in resource "kubernetes_secret" "github_registry_auth":
 106: resource "kubernetes_secret" "github_registry_auth" {
```

### Expected Behavior
`kubernetes_secret` should be created, since the other k8s resources are worked on successfully.

### Actual Behavior
`kubernetes_secret` used default kubernetes host parameters, resulting in a call to `localhost`.
This is weird since other stuff on the kubernetes provider works fine.

### Steps to Reproduce
1. `terraform apply`

### References
https://github.com/ironPeakServices/infrastructure/tree/feat/argo

**Comment by mbarrien** [comment]
The helm and kubernetes providers are separate providers that need separate configuration. Your codebase in main.tf only has a `provider "helm"` block and is missing a `provider "kubernetes"` block. You should be able to copy everything inside the `kubernetes {}` block inside your helm provider configuration and put it inside a `provider "kubernetes" {}` declaration.

**Comment by hazcod** [comment]
Hi @mbarrien , see https://github.com/ironPeakServices/infrastructure/blob/master/modules/helm/main.tf

**Comment by mbarrien** [comment]
I said I looked at main.tf. Repeating what I said above, you only have a `provider "helm"` block and no `provider "kubernetes"` block. You need both.

**Comment by hazcod** [comment]
Seems to work if I centralize provider config in the root module, closing.
Thank you @mbarrien
