### ISSUE TITLE
Cannot deploy when Gitlab CI environment is specified

### ISSUE THREAD

**Issue by L3tum** [terraform-providers/terraform-provider-kubernetes#792]
Righty, this is going to sound insane, and it cost us 3 days to actually find out about it. I'm not sure where I should open this report, but I figured this project is the best start.

Anyways, the meat of the problem is that, once the `environment` in a `.gitlab-ci.yaml` is specified, terraform cannot connect to our kubernetes cluster anymore.

### Terraform Version
Tested from v0.12.21 to v0.12.23, with this provider always in 1.11.1

### Affected Resource(s)
- deployment (patch, create, delete) of any resource

### Terraform Configuration Files
It is not related to our config and I unfortunately can't post it anyways.

### Debug Output
The debug output is useless in this case sadly.

### Panic Output
`Error: Failed to update service: services "[service]" is forbidden: User "[correct user]" cannot patch resource "services" in API group "" in the namespace "[correct namespace]"`

### Expected Behavior
Able to deploy (`terraform apply`)

### Actual Behavior
See above. API calls return a 403 Forbidden

### Steps to Reproduce
Right, I'm not sure if it is reproducable. I'm still not sure *why* this happened, just that I found the cause for it. We haven't had time or resources for a root cause analysis.
1. Make a simple terraform kubernetes application (just one secret or whatever)
2. Create a gitlab-ci script that deploys your terraform files to kubernetes in a job that is marked with the `environment` specification ([Environment](https://docs.gitlab.com/ee/ci/environments.html))
3. Observe fail.

### Important Factoids
We're using RBAC and AWS EKS. The Gitlab Runner assumes an IAM Role via `aws-iam-authenticator` that has the required access policies set correctly. Login works just deployment doesn't. 
There isn't anything else necessarily specific about our setup. 

### References
I haven't found anything to this. Honestly, this is mostly so if someone else stumbles upon the same problem that they know what causes it and maybe someone here is more knowledgeable and can explain me why this happens or can even fix it. 

Important to note is also that if we just remove the `environment` flag and change literally nothing else whatsoever, same runner, same image, same everything, that it works, so the 403 is *definitely* caused by that, just not sure why or how, and also not sure if it's a problem in gitlab ci, terraform, kubernetes, this provider....

**Comment by aareet** [comment]
@L3tum thank you for the report. Unfortunately if this is not reproducible it's not something we'll be able to help with. I'm glad you've shared all these details here and it will most likely help anyone else who stumbles upon a similar problem. For now, I'll close this issue, but if someone comes across this and is able to help us reproduce, please reopen.
