### ISSUE TITLE
Feature request: kubernetes_deployment without waiting for rollout

### ISSUE THREAD

**Issue by MateuszStefek** [terraform-providers/terraform-provider-kubernetes#797]
Currently, when you apply `kubernetes_deployment`, terraform waits for the rollout to complete with success.

I would like to have an option to ignore this. Sometimes, the reason the rollout fails is not a fault of the infrastructure managed by my Terraform definition. For instance, Docker registry which I'm using might be down.

In other words, I would like to use `kubernetes_deployment` in a similar way as with `kubectl apply -f`.

**Comment by abhijithkumar123** [comment]
Sometimes the apply fails for me saying the following:

> Error: Waiting for rollout to finish: 1 old replicas are pending termination...

That old replica would have got terminated but terraform wouldn't wait for it to happen and fails.

**Comment by dsymonds** [comment]
This is covered by #605.

**Comment by aareet** [comment]
Closing in favour of #605, we will track status there
