### ISSUE TITLE
resource "kubernetes_storage_class" does not support "mount_options"

### ISSUE THREAD

**Issue by omichels** [terraform-providers/terraform-provider-kubernetes#804]
### Terraform Version
Terraform v0.12.24
+ provider.azurerm v2.3.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.7.0

### Affected Resource(s)
```hcl
resource "kubernetes_storage_class" "example" {
  metadata {
    name = "terraform-example"
  }
  storage_provisioner = "kubernetes.io/gce-pd"
  reclaim_policy      = "Retain"
  parameters = {
    type = "pd-standard"
  }
  mount_options = ["file_mode=0700", "dir_mode=0777", "mfsymlinks", "uid=1000", "gid=1000", "nobrl", "cache=none"]
}```

### Expected Behavior
storageclass should get created

### Actual Behavior

Error: Unsupported argument

  on ../modules/azurestorageclasses/main.tf line 7, in resource "kubernetes_storage_class" "azurefile-sc-solr2":
   7:   mount_option = [ "file_mode=0770", "dir_mode=0770", "mfsymlinks", "uid=8983", "gid=8983", "nobrl", "cache=none" ]

An argument named "mount_option" is not expected here.



### Steps to Reproduce
1. `terraform apply`

**Comment by mbarrien** [comment]
It's spelled mount_options with an "s"

https://www.terraform.io/docs/providers/kubernetes/r/storage_class.html

**Comment by omichels** [comment]
if was testing "mount_option", "mount_options" and "mountOptions"

$ terraform plan -var-file="../common/common.tfvars"

Error: Unsupported argument

  on ../modules/azurestorageclasses/main.tf line 7, in resource "kubernetes_storage_class" "azurefile-sc-solr2":
   7:   mount_options = [ "file_mode=0770", "dir_mode=0770", "mfsymlinks", "uid=8983", "gid=8983", "nobrl", "cache=none" ]

An argument named "mount_options" is not expected here.

**Comment by omichels** [comment]
i didn't realize that "mount_options" is only supported since version 1.11.0 of the kubernetes provider
