### ISSUE TITLE
Error while creating a kubernetes_namespace with error metadata.0.name a DNS-1123 subdomain

### ISSUE THREAD

**Issue by dj-wasabi** [terraform-providers/terraform-provider-kubernetes#819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

`kubernetes_namespace`

### Terraform Configuration Files
```hcl
variable "myNamespaces" {
    description = "list of namespaces to create"
    type        = list(string)
    default     = ["configuration", "myOtherNameSpace"]
}
resource "kubernetes_namespace" "helm_repo" {
    count     = length(var.myNamespaces)

    metadata {
        name = element(var.myNamespaces, count.index)

        annotations = {
            name = element(var.myNamespaces, count.index)
        }
    }
}
```

### Expected Behavior
What should have happened?

Creation of 2 namespaces in Kubernetes

### Actual Behavior
What actually happened?

An error occured:
```
Error: metadata.0.name a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

  on ../terraform-helm/src/kubectl.tf line 19, in resource "kubernetes_namespace" "helm_repo":
  19: resource "kubernetes_namespace" "helm_repo" {
```

### Steps to Reproduce

1. terraform init;
2. terraform apply;

**Comment by nmusatti** [comment]
I believe "myOtherNameSpace" is not a valid name for a namespace, as explained in the error message you posted.

**Comment by dj-wasabi** [comment]
Ah, my bad (need more sleep). Sorry!
