### ISSUE TITLE
kubernetes_validating_webhook_configuration namespace is not supported in schema

### ISSUE THREAD

**Issue by akhilmanikandan** [terraform-providers/terraform-provider-kubernetes#846]
According to the Terraform documentation [documentation](https://www.terraform.io/docs/providers/kubernetes/r/validating_webhook_configuration.html)  the **kubernetes_validating_webhook_configuration**  supports **namespace** in **metadata**

But when  performed **terraform validate** with  namespace the following error gets thrown.

```
Error: Unsupported argument

  on _<my module>_ line 527, in resource "kubernetes_validating_webhook_configuration" "_<my resource name>_":
 527:    namespace = "_<my namespace>"

An argument named "namespace" is not expected here.
```

![Annotation 2020-05-17 111455](https://user-images.githubusercontent.com/30230324/82133456-c12c1d00-982f-11ea-8231-53b2ef8d6a6e.png)

**Comment by aareet** [comment]
@akhilmanikandan nice catch, the documentation is actually incorrect - validating_webhook_configuration cannot be namespaced and applies to the whole cluster. We'll remove that from our documentation. The validate behaviour is accurate.
