### ISSUE TITLE
Datasource kubernetes_Service with labels

### ISSUE THREAD

**Issue by jeusdi** [terraform-providers/terraform-provider-kubernetes#854]
I've tried to get a service using `kubernetes_service` according to labels:

```
data "kubernetes_service" "spark_master_service" {
    metadata {
        labels = {
            app.kubernetes.io/component = master
            app.kubernetes.io/instance = spark
            app.kubernetes.io/name = spark
        }
    }
}
```

I'm getting these error messages:

```
Error: Reference to undeclared resource

  on main.tf line 51, in data "kubernetes_service" "spark_master_service":
  51:             app.kubernetes.io/component = master

A managed resource "app" "kubernetes" has not been declared in the root
module.


Error: Invalid reference

  on main.tf line 51, in data "kubernetes_service" "spark_master_service":
  51:             app.kubernetes.io/component = master

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.


Error: Invalid reference

  on main.tf line 51, in data "kubernetes_service" "spark_master_service":
  51:             app.kubernetes.io/component = master

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.


Error: Reference to undeclared resource

  on main.tf line 52, in data "kubernetes_service" "spark_master_service":
  52:             app.kubernetes.io/instance = spark

A managed resource "app" "kubernetes" has not been declared in the root
module.


Error: Invalid reference

  on main.tf line 52, in data "kubernetes_service" "spark_master_service":
  52:             app.kubernetes.io/instance = spark

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.


Error: Invalid reference

  on main.tf line 52, in data "kubernetes_service" "spark_master_service":
  52:             app.kubernetes.io/instance = spark

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.
```

Any ideas?

**Comment by mbarrien** [comment]
This is Terraform syntax, not a provider issue.

Use quotes around the keys.

**Comment by jeusdi** [comment]
Sorry @mbarrien 

Currently, I'm getting this error message I don't quite figure out what does it mean?

    Error: resource name may not be empty
    
      on main.tf line 48, in data "kubernetes_service" "spark_master_service":
      48: data "kubernetes_service" "spark_master_service" {

Related `data source`:

    data "kubernetes_service" "spark_master_service" {
        metadata {
            labels = {
                "app.kubernetes.io/component" = "master"
                "app.kubernetes.io/instance" = "spark"
                "app.kubernetes.io/name" = "spark"
            }
            namespace = var.namespace
        }
    }

My `data` has a name... I don't quite figure out what terraform is telling me...


Any ideas?

**Comment by mbarrien** [comment]
Go see <https://www.terraform.io/docs/providers/kubernetes/d/service.html>. You must match on the actual name field in the metadata, and not just have a label called name.

**Comment by jeusdi** [comment]
Here my service I'd like to match:

```
+ kubectl get service spark-master-svc -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-25T14:49:12Z"
  labels:
    app.kubernetes.io/instance: spark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-1.2.21
  name: spark-master-svc
  namespace: ra-iot-dev
  resourceVersion: "221884011"
  selfLink: /api/v1/namespaces/ra-iot-dev/services/spark-master-svc
  uid: e5a3a906-9e96-11ea-9e39-0050569f5f65
spec:
  clusterIP: 172.30.134.177
  ports:
  - name: cluster
    port: 7077
    protocol: TCP
    targetPort: cluster
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: spark
    app.kubernetes.io/name: spark
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

The problem is that:

 * IIt's mandatory a `metadata.name`?
 * or, the problem is that I've set a label `app.kubernetes.io/name`?
 * What about if you need to match only by labels?

**Comment by mbarrien** [comment]
We've veered way off... GitHub issues aren't a support forum. I was just trying to note that this isn't a bug.

Anyways... providing metadata.name is mandatory in the provider's implementation of kubernetes_service, since it must match exactly one item. (The docs are wrong in that metadata.name is mandatory not optional, and all other fields other than namespace are ignored.) There is no problem with the label "app.kubernetes.io/name", it's just not how kubernetes_service data source works.
