### ISSUE TITLE
kubernetes_pod timeout

### ISSUE THREAD

**Issue by mahmoudian1** [terraform-providers/terraform-provider-kubernetes#91]
Hi there,

It would be nice if we can control the timeout in creation and especially destroy for some large images that takes to pull more than 5 minutes.

Error on create:
> kubernetes_pod.xxx: timeout while waiting for state to become 'Running' (last state: 'Pending', timeout: 5m0s)

error on destroy:
>kubernetes_pod.xxx: Still destroying... (ID: default/xxx-1, 1m0s elapsed)
>Error: Error applying plan:
>3 error(s) occurred:
>* kubernetes_pod.xxx (destroy): 1 error(s) occurred:
>* kubernetes_pod.xxx: Pod java-xxx-1 still exists (Pending)

**Comment by radeksimko** [comment]
Hey @mahmoudian1 
totally agreed, we can add customizable timeouts for this.
