### ISSUE TITLE
Error when annotation contains a slash

### ISSUE THREAD

**Issue by sagikazarmark** [terraform-providers/terraform-provider-kubernetes#93]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.0
+ provider.aws v0.1.4
+ provider.kubernetes v1.0.1
+ provider.null v1.0.0
+ provider.random v1.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_replication_controller

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "kubernetes_replication_controller" "default" {
    metadata {
        name      = "${var.name}"
        namespace = "${var.namespace}"

        annotations {
            "prometheus.io/scrape" = "true"
            "prometheus.io/port"   = "9104"
        }
    }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform should have updated the resource.

### Actual Behavior
Terraform failed with the following message:

`* kubernetes_replication_controller.default: Failed to update replication controller: jsonpatch add operation does not apply: doc is missing path: /metadata/annotations/prometheus.io~1scrape`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

- #37 
- #40

**Comment by acobaugh** [comment]
Just hit this as well trying to set `external-dns.alpha.kubernetes.io/hostname` (without #50 applied) on a service. I thought #40 was supposed to fix this?

**Comment by eflatdiminished** [comment]
Having the same issue with:
    Terraform v0.11.3
      + provider.aws v1.9.0
      + provider.null v1.0.0
when trying to create tags for an AWS VPC. Here is the message:
`Error parsing: expected '/' for comment`

**Comment by radeksimko** [comment]
Hi folks,
thanks for reporting this bug and sorry for the delay in processing it!

Based on the error message mentioned

> * kubernetes_replication_controller.default: Failed to update replication controller: jsonpatch add operation does not apply: doc is missing path: /metadata/annotations/prometheus.io~1scrape

I believe this was fixed by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/116 which will be part of the next release coming out 🔜. For that reason I'm going to close it.

-----

@eflatdiminished This looks like an issue related to the [AWS provider](github.com/terraform-providers/terraform-provider-aws). Do you mind reporting it there and attaching repro case in the form of a config? Thanks.
