### ISSUE TITLE
Feature Request: max_retries option for provider block

### ISSUE THREAD

**Issue by kbruner** [terraform-providers/terraform-provider-kubernetes#96]
Requesting support for a `max_retries` option for the kubernetes provider.

Sample use case:  When creating a cluster via terraform, I also want to populate some ConfigMaps with terraform outputs.  It does take a few minutes for the kubernetes API to come up, so being able to increase the retry limit so the resources can live in the same `.tf` files as the cluster infrastructure and succeed on the same `terraform apply`.

**Comment by paultyng** [comment]
This seems like the upstream progressive apply issue: https://github.com/hashicorp/terraform/issues/4149

You cannot currently chain together a provider's config with the output of a resource (including a resource creating that cluster).

**Comment by rchernobelskiy** [comment]
Is there a way to have it retry if the api server has a momentary hiccup?

(Just as an aside, the progressive apply works fine with aws/eks)
