### ISSUE TITLE
Updating environment variables has no effect because pod is not recreated

### ISSUE THREAD

**Issue by arekkas** [terraform-providers/terraform-provider-kubernetes#98]
I am using terraform and this provider to deploy images

### Terraform Version

Terraform v0.11.1

### Affected Resource(s)

- kubernetes_pod

### Terraform Configuration Files

```hcl
resource "kubernetes_pod" "hello" {
  metadata {
    name = "hello"
    labels {
      app = "hello"
    }

    namespace = "${kubernetes_namespace.ory_cloud_platform.id}"
  }

  spec {
    container {
      name = "nodejs-hello"
      image = "brianfive/simple-express-docker"

      env {
        name = "FOO"
        value = "bar"
      }
    }

    restart_policy = "OnFailure"
  }
}
```

Running `terraform plan && terraform apply` works fine. Then, changing `value = "bar"` to `value = "baz"` and then applying `terraform plan` yields the following plan:

```
  ~ module.k8s_platform.kubernetes_pod.hello
      spec.0.container.0.env.0.value: "bar" => "baz"
```

Applying this plan with `terraform plan` has no effect in Kubernetes. Rerunning `terraform plan` yields the same execution plan:

```
  ~ module.k8s_platform.kubernetes_pod.hello
      spec.0.container.0.env.0.value: "bar" => "baz"
```

### Expected Behavior

The environment variable change should have been applied. For this, the pod has to be recreated. I applied the same change directly to the configuration of the file which yielded the following result:

![screenshot-2017-12-11 kubernetes dashboard](https://user-images.githubusercontent.com/3372410/33852535-3a4483d4-debb-11e7-87fe-b1be660a9dfa.png)

![screenshot-2017-12-11 kubernetes dashboard 1](https://user-images.githubusercontent.com/3372410/33852538-3b63e1ba-debb-11e7-8f83-f21e6024dc55.png)

### Actual Behavior

The change was not applied because the pod was not recreated. Recreation is neccesary for environment variable updates.

### Important Factoids

The Kubernetes cluster is a Google Container Engine / Managed Kuberenetes.

**Comment by worrel** [comment]
Note that the pod doesn't get recreated if you change the env var name either - or even if you re-order the env vars.  It does however respond to a change in the # of env vars - so adding an extra dummy variable will trigger recreation.  That's not a great solution though.

FWIW I'm resorting to `terraform taint <pod-with-changed-env>` until this is resolved.
